// Mocks generated by Mockito 5.4.6 from annotations
// in note_synapse/test/immutability_enforcement_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:note_synapse/models/workflow_binding_row.dart' as _i4;
import 'package:note_synapse/services/tag_workflow_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TagWorkflowService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagWorkflowService extends _i1.Mock
    implements _i2.TagWorkflowService {
  MockTagWorkflowService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i2.ResolvedBinding>> resolveBindings(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#resolveBindings, [tags]),
            returnValue: _i3.Future<List<_i2.ResolvedBinding>>.value(
              <_i2.ResolvedBinding>[],
            ),
          )
          as _i3.Future<List<_i2.ResolvedBinding>>);

  @override
  _i3.Future<bool> hasImmutableBinding(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#hasImmutableBinding, [tags]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.WorkflowBindingRow?> getBindingByPattern(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#getBindingByPattern, [pattern]),
            returnValue: _i3.Future<_i4.WorkflowBindingRow?>.value(),
          )
          as _i3.Future<_i4.WorkflowBindingRow?>);

  @override
  _i3.Future<List<_i4.WorkflowBindingRow>> getAllBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBindings, []),
            returnValue: _i3.Future<List<_i4.WorkflowBindingRow>>.value(
              <_i4.WorkflowBindingRow>[],
            ),
          )
          as _i3.Future<List<_i4.WorkflowBindingRow>>);

  @override
  _i3.Future<void> registerBinding({
    required String? pattern,
    required bool? isPrefix,
    required String? skillNoteId,
    required String? prompt,
    required bool? contentImmutable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerBinding, [], {
              #pattern: pattern,
              #isPrefix: isPrefix,
              #skillNoteId: skillNoteId,
              #prompt: prompt,
              #contentImmutable: contentImmutable,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeBinding(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#removeBinding, [pattern]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
