import 'package:flutter_test/flutter_test.dart';
import 'package:note_synapse/models/generation_context.dart';
import 'package:note_synapse/models/model_config.dart';
import 'package:note_synapse/models/model_type.dart';
import 'package:note_synapse/services/model_preference_service.dart';
import 'package:note_synapse/services/model_selector.dart';
import 'package:note_synapse/services/model_storage_service.dart';
import 'package:note_synapse/services/models/ai_model.dart';
import 'package:note_synapse/services/prompts/prompt_models.dart';
import 'package:shared_preferences/shared_preferences.dart';

class _FakeModel extends AIModel {
  _FakeModel(this.ready, this.modelType);

  final bool ready;
  final ModelType modelType;
  var generateCalls = 0;
  ModelConfig? initializedWith;

  @override
  String get id => modelType.id;

  @override
  String get name => modelType.displayName;

  @override
  String get description => 'test model';

  @override
  Future<void> initialize({ModelConfig? config}) async {
    initializedWith = config;
  }

  @override
  Future<bool> isReady() async => ready;

  @override
  Future<String> generateWithMessages(
    List<PromptMessage> messages, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    GenerationContext? generationContext,
  }) async {
    generateCalls += 1;
    return 'generated by ${modelType.id}';
  }

  @override
  Future<void> dispose() async {}
}

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('exact generation never falls back to the ready active model', () async {
    SharedPreferences.setMockInitialValues({});
    final remote = _FakeModel(true, ModelType.gemini);
    final unavailableLocal = _FakeModel(false, ModelType.localMnn);
    final selector = ModelSelector(
      ModelStorageService(),
      ModelPreferenceService(),
      modelFactory: (type) => switch (type) {
        ModelType.gemini => remote,
        ModelType.localMnn => unavailableLocal,
        ModelType.openaiCompatible => _FakeModel(true, type),
      },
    );
    await selector.switchToModel(
      ModelConfig(id: 'active-remote', type: ModelType.gemini),
    );
    final approved = ModelConfig(
      id: 'approved-local',
      type: ModelType.localMnn,
      displayName: 'Approved local',
    );
    final request = PromptRequest.singleTurn(
      systemMessage: const PromptMessage(
        role: PromptRole.system,
        content: 'system',
      ),
      userMessage: const PromptMessage(
        role: PromptRole.user,
        content: 'sensitive payload',
      ),
    );

    await expectLater(
      selector.generateFromPromptExact(request, config: approved),
      throwsStateError,
    );
    expect(remote.generateCalls, 0);
    expect(unavailableLocal.generateCalls, 0);
    expect(unavailableLocal.initializedWith, approved);
  });
}
