import 'dart:async';

import 'package:file_picker/file_picker.dart';

import '../models/conversation.dart';
import '../models/mcp_endpoint.dart';
import '../models/model_type.dart';
import '../models/generation_context.dart';
import '../services/logger_service.dart';
import '../services/mcp_tool_integration_service.dart';
import '../services/model_selector.dart';
import '../services/models/local_mnn_model.dart';
import '../services/service_locator.dart';
import '../services/prompts/prompt_models.dart';
import '../services/prompts/system_prompt_builder.dart';
import '../services/prompts/registrations/chat_prompt_configuration.dart';
import 'conversation_settings_service.dart';
import 'prompts/prompt_configuration_service.dart';

class ConversationCancelledException implements Exception {
  const ConversationCancelledException([
    this.message = 'Request cancelled by user',
  ]);

  final String message;

  @override
  String toString() => message;
}

class ConversationAiResponse {
  const ConversationAiResponse({required this.content, this.metadata});

  final String content;
  final Map<String, dynamic>? metadata;
}

typedef ToolExecutionCallback =
    Future<String> Function(
      String serviceName,
      String toolName,
      Map<String, dynamic> params,
      GenerationContext generationContext,
    );

typedef ActiveToolsProvider = Map<String, List<McpTool>> Function();

typedef CancellationCheck = bool Function();
typedef IterationsExhaustedHandler = Future<int?> Function(int exhaustedLimit);

class ConversationAiEngine {
  const ConversationAiEngine();

  /// Converts stored [ConversationMessage]s into [PromptMessage]s for model
  /// consumption. Handles role conversion for model mismatches, modelUsed
  /// metadata propagation, timestamp context, attachment loading, and tool
  /// result injection.
  ///
  /// Used by both conversation_chat_screen and immersive_note_screen.
  static Future<List<PromptMessage>> buildConversationMessages({
    required List<ConversationMessage> messages,
    required String? currentModelId,
    required Future<List<PlatformFile>> Function(ConversationMessage)
    loadAttachments,
  }) async {
    final conversationMessages = <PromptMessage>[];

    for (final message in messages) {
      // Filter out synthesized error messages
      if (message.metadata?['isSynthesized'] == true) {
        continue;
      }

      var role = message.type == MessageType.user
          ? PromptRole.user
          : PromptRole.assistant;
      var content = message.content;

      // Resolve modelUsed: prefer the DB column, fall back to metadata.
      // The DB column is always populated for saved messages; metadata may
      // or may not contain it depending on how the message was originally saved.
      final modelUsed =
          message.modelUsed ?? message.metadata?['modelUsed'] as String?;

      // If the message was generated by a different model, treat it as a user
      // message to avoid potential format/capability mismatches (e.g.
      // thoughtSignature). When modelUsed is null (legacy messages), we
      // cautiously treat it as a different model to avoid generation failures.
      if (role == PromptRole.assistant) {
        if (currentModelId != null &&
            (modelUsed == null || modelUsed != currentModelId)) {
          role = PromptRole.user;
          final modelLabel = modelUsed ?? 'an earlier model';
          content = '[Response from $modelLabel]:\n$content';
        }
      }

      // Prepend every user message with a timestamp context message.
      if (role == PromptRole.user) {
        final messageTimeContext = SystemPromptBuilder.formatTimestamp(
          message.timestamp,
        );
        final perMessageAddOn = PromptConfigurationService.instance.getValue(
          ChatPromptConfiguration.perMessageAddendumId,
        );
        final buffer = StringBuffer()
          ..write('Message created at: $messageTimeContext');
        if (perMessageAddOn != null && perMessageAddOn.trim().isNotEmpty) {
          buffer
            ..writeln()
            ..write(perMessageAddOn.trim());
        }
        conversationMessages.add(
          PromptMessage(role: PromptRole.user, content: buffer.toString()),
        );
      }

      final attachments = await loadAttachments(message);

      // Ensure modelUsed is in metadata so downstream model layers (e.g.
      // Gemini's isModelMatch) can read it.
      final effectiveMetadata = <String, dynamic>{
        ...?message.metadata,
        if (message.modelUsed != null && message.metadata?['modelUsed'] == null)
          'modelUsed': message.modelUsed,
      };

      final promptMessage = PromptMessage(
        role: role,
        content: content,
        attachments: attachments,
        metadata: effectiveMetadata.isNotEmpty ? effectiveMetadata : null,
      );

      conversationMessages.add(promptMessage);

      // Add tool results from assistant messages that kept their role
      if (role == PromptRole.assistant) {
        final toolCallsWithResults =
            message.metadata?['tool_calls_with_results'] as List?;
        if (toolCallsWithResults != null && toolCallsWithResults.isNotEmpty) {
          for (final entry in toolCallsWithResults) {
            final toolCallId = entry['id'];
            final toolResult = entry['result'] as String? ?? '';
            conversationMessages.add(
              PromptMessage(
                role: PromptRole.tool,
                content: toolResult,
                metadata: {
                  if (toolCallId != null) 'tool_call_id': toolCallId,
                  ...((entry is Map<String, dynamic>) ? entry : {}),
                },
              ),
            );
          }
        }
      }
    }

    return conversationMessages;
  }

  Future<ConversationAiResponse> generate({
    required PromptRequest request,
    required Map<String, List<McpTool>> activeTools,
    ActiveToolsProvider? activeToolsProvider,
    required bool enableTools,
    required ToolExecutionCallback executeTool,
    required CancellationCheck isCancelled,
    required GenerationContext generationContext,
    int? maxToolIterations,
    IterationsExhaustedHandler? onIterationsExhausted,
    void Function(String chunk)? onStreamChunk,
  }) async {
    if (isCancelled()) {
      throw const ConversationCancelledException();
    }

    // Always use the tool-enabled path to ensure consistent handling of parts_history
    // and other metadata, even if no tools are active.
    return _generateWithTools(
      request: request,
      activeTools: activeTools,
      activeToolsProvider: activeToolsProvider,
      executeTool: executeTool,
      isCancelled: isCancelled,
      generationContext: generationContext,
      maxToolIterations: maxToolIterations,
      onIterationsExhausted: onIterationsExhausted,
      onStreamChunk: onStreamChunk,
    );
  }

  /// Generate a response with tool-calling support.
  ///
  /// Tool descriptions reach the model through three complementary paths:
  ///
  /// 1. **System prompt text catalog** (`buildMcpSystemPrompt`) — built by the
  ///    caller (e.g. conversation_chat_screen) and embedded in the system
  ///    message. Skipped for models with [AIModel.usesNativeToolDeclarations].
  ///
  /// 2. **Native tool declarations** (`buildToolDeclarations`) — structured
  ///    schemas passed alongside the request. Cloud models get a single
  ///    `call_tool` wrapper; local models get individual per-tool declarations
  ///    for constrained decoding.
  ///
  /// 3. **Mid-conversation discovery** (`_buildDynamicToolDiscoveryMessage`) —
  ///    injected as a system message when new tools appear between iterations
  ///    (e.g. after a skill loads an MCP endpoint). Local models get a compact
  ///    list; cloud models get the full text catalog.
  Future<ConversationAiResponse> _generateWithTools({
    required PromptRequest request,
    required Map<String, List<McpTool>> activeTools,
    ActiveToolsProvider? activeToolsProvider,
    required ToolExecutionCallback executeTool,
    required CancellationCheck isCancelled,
    required GenerationContext generationContext,
    int? maxToolIterations,
    IterationsExhaustedHandler? onIterationsExhausted,
    void Function(String chunk)? onStreamChunk,
  }) async {
    try {
      final requestId = generationContext.ensureRequestId();
      if (isCancelled()) {
        throw const ConversationCancelledException();
      }

      var currentMessages = <PromptMessage>[
        request.systemMessage,
        ...request.contextMessages,
        ...request.conversationMessages,
      ];

      Map<String, List<McpTool>> resolveActiveTools() {
        final resolved = activeToolsProvider?.call() ?? activeTools;
        return {
          for (final entry in resolved.entries)
            entry.key: List<McpTool>.unmodifiable(entry.value),
        };
      }

      final modelSelector = getIt<ModelSelector>();
      var currentActiveTools = resolveActiveTools();
      final announcedToolKeys = _toolKeys(currentActiveTools);
      List<Map<String, dynamic>>? cachedToolDeclarations;

      LoggerService.info(
        'Starting conversation with ${currentActiveTools.length} tools',
        error: {'requestId': requestId},
      );

      int iterationLimit =
          maxToolIterations ??
          ConversationSettingsService.defaultMaxToolIterations;
      iterationLimit =
          iterationLimit < ConversationSettingsService.minToolIterations
          ? ConversationSettingsService.minToolIterations
          : (iterationLimit > ConversationSettingsService.maxToolIterationsCap
                ? ConversationSettingsService.maxToolIterationsCap
                : iterationLimit);
      var iteration = 0;
      final conversationParts = <String>[];
      Map<String, dynamic>? lastAssistantMetadata;

      // Streaming-first for local models: stream with tool awareness.
      // If pure text, return fast. If tool calls detected, seed and enter
      // the tool loop for execution. Only applies without model override.
      final activeModel = generationContext.modelOverride == null
          ? modelSelector.currentModel
          : null;
      Map<String, dynamic>? streamingFirstResult;
      if (activeModel is LocalMnnModel &&
          activeModel.supportsStreaming &&
          onStreamChunk != null) {
        final toolDeclarations = getIt<ModelSelector>().buildToolDeclarations(
          currentActiveTools,
          generationContext: generationContext,
        );
        final result = await activeModel.generateStreamingWithTools(
          currentMessages,
          toolDeclarations,
          onChunk: (chunk) {
            if (isCancelled()) return;
            onStreamChunk(chunk);
          },
          generationContext: generationContext,
        );
        if (isCancelled()) throw const ConversationCancelledException();

        final calls = result['function_calls'] as List?;
        if (calls == null || calls.isEmpty) {
          // Pure text — fast streaming return
          return ConversationAiResponse(
            content: result['text'] as String? ?? '',
            metadata: {'modelUsed': activeModel.name},
          );
        }
        // Tool calls detected — store result and fall through to tool loop
        streamingFirstResult = result;
      }

      while (true) {
        if (iteration >= iterationLimit) {
          if (onIterationsExhausted != null) {
            final nextLimit = await onIterationsExhausted(iterationLimit);
            if (nextLimit == null) {
              throw const ConversationCancelledException(
                'Tool iteration limit reached and user aborted.',
              );
            }
            final sanitizedNext =
                nextLimit < ConversationSettingsService.minToolIterations
                ? ConversationSettingsService.minToolIterations
                : (nextLimit > ConversationSettingsService.maxToolIterationsCap
                      ? ConversationSettingsService.maxToolIterationsCap
                      : nextLimit);
            if (sanitizedNext <= iterationLimit) {
              LoggerService.warning(
                'Rejected iteration limit $nextLimit (must be greater than $iterationLimit)',
              );
              continue;
            }
            iterationLimit = sanitizedNext;
            continue;
          }

          LoggerService.warning(
            'MCP tool loop exceeded $iterationLimit iterations',
          );
          return const ConversationAiResponse(
            content:
                'I was unable to complete the request with the available tools. Please try again later.',
            metadata: {'isSynthesized': true},
          );
        }

        if (isCancelled()) {
          throw const ConversationCancelledException();
        }

        LoggerService.debug('MCP iteration ${iteration + 1}/$iterationLimit');

        currentActiveTools = resolveActiveTools();

        // Use streaming-first result if available (first iteration only),
        // otherwise generate normally with cached tool declarations.
        final Map<String, dynamic> response;
        if (streamingFirstResult != null) {
          response = streamingFirstResult;
          streamingFirstResult = null;
        } else {
          cachedToolDeclarations ??= getIt<ModelSelector>()
              .buildToolDeclarations(
                currentActiveTools,
                generationContext: generationContext,
              );
          response = await getIt<ModelSelector>()
              .generateWithToolsAndMessages(
                currentMessages,
                cachedToolDeclarations,
                generationContext: generationContext,
              );
        }

        if (isCancelled()) {
          throw const ConversationCancelledException();
        }

        final textResponse = response['text'] as String?;
        final functionCalls = response['function_calls'] as List?;
        final partsHistory = response['parts_history'] as List?;

        if (functionCalls != null && functionCalls.isNotEmpty) {
          LoggerService.info(
            'AI requested ${functionCalls.length} tool call(s)',
          );

          final toolResults = <String>[];
          final toolCallsWithResults = <Map<String, dynamic>>[];

          for (int i = 0; i < functionCalls.length; i++) {
            if (isCancelled()) {
              throw const ConversationCancelledException();
            }

            final functionCall = functionCalls[i] as Map<String, dynamic>;
            final functionName = functionCall['name'] as String;
            final rawArgs = functionCall['args'];

            LoggerService.debug(
              'Processing function call',
              error: {'functionName': functionName, 'args': rawArgs},
            );

            String? serviceName;
            String? toolName;
            Map<String, dynamic>? params;

            if (functionName != 'call_tool') {
              final directTool = _resolveDirectToolCall(
                functionName,
                currentActiveTools,
              );
              if (directTool != null) {
                final parsedArgs =
                    McpToolIntegrationService.parseCallToolArguments(
                      rawArgs,
                      fallbackServiceName: directTool['service_name'],
                      fallbackToolName: directTool['tool_name'],
                      logErrors: false,
                    );
                serviceName =
                    (parsedArgs?['service_name'] as String?) ??
                    directTool['service_name']!;
                toolName =
                    (parsedArgs?['tool_name'] as String?) ??
                    directTool['tool_name']!;
                params =
                    parsedArgs?['params'] as Map<String, dynamic>? ??
                    (rawArgs is Map<String, dynamic>
                        ? Map<String, dynamic>.from(rawArgs)
                        : rawArgs is Map
                        ? rawArgs.map(
                            (key, value) => MapEntry(key.toString(), value),
                          )
                        : <String, dynamic>{});
              } else {
                // Model called a tool directly by name instead of using call_tool wrapper
                // Return an error with helpful guidance (like "command not found" helper)
                final errorMessage = _buildUnknownToolErrorMessage(
                  functionName,
                  rawArgs,
                  activeTools,
                );

                LoggerService.warning(
                  'Unknown function call: $functionName, returning error to LLM',
                );

                final errorResult = 'Error: $errorMessage';
                toolResults.add(errorResult);
                conversationParts.add(
                  '[Tool error: Unknown function "$functionName"]',
                );

                // Build proper tool error message based on model type
                if (getIt<ModelSelector>().currentModelConfig?.type ==
                    ModelType.openaiCompatible) {
                  // OpenAI: Use the original tool_call_id from the API response
                  final toolCallId =
                      functionCall['id'] as String? ??
                      't_err_${DateTime.now().millisecondsSinceEpoch.toRadixString(36)}_$i';
                  toolCallsWithResults.add({
                    'id': toolCallId,
                    'function_call': functionCall,
                    'result': errorResult,
                  });
                } else {
                  // Gemini: Store with function metadata for proper functionResponse format
                  toolCallsWithResults.add({
                    'function_name': functionName,
                    'function_args': rawArgs,
                    'result': errorResult,
                    // Preserve thought_signature for Gemini 3+ models
                    if (functionCall.containsKey('thoughtSignature'))
                      'thought_signature': functionCall['thoughtSignature'],
                  });
                }

                continue;
              }
            } else {
              final parsedArgs =
                  McpToolIntegrationService.parseCallToolArguments(rawArgs);
              if (parsedArgs == null) {
                LoggerService.error(
                  'Failed to parse call_tool arguments',
                  error: {'args': rawArgs},
                );
                continue;
              }

              serviceName = parsedArgs['service_name'] as String;
              toolName = parsedArgs['tool_name'] as String;
              params = parsedArgs['params'] as Map<String, dynamic>;
            }

            LoggerService.info('Executing: $serviceName.$toolName');
            LoggerService.debug('Tool parameters', error: params);

            try {
              final result = await executeTool(
                serviceName,
                toolName,
                params,
                generationContext,
              );
              final toolSummary =
                  'Tool: $serviceName.$toolName\nResult: $result';
              toolResults.add(toolSummary);
              conversationParts.add('[Tool executed: $serviceName.$toolName]');

              if (getIt<ModelSelector>().currentModelConfig?.type ==
                  ModelType.openaiCompatible) {
                // Use the original tool_call_id from the API response if available
                final toolCallId =
                    functionCall['id'] as String? ??
                    't_${DateTime.now().millisecondsSinceEpoch.toRadixString(36)}_${toolName.length > 10 ? toolName.substring(0, 10) : toolName}_$i';
                toolCallsWithResults.add({
                  'id': toolCallId,
                  'function_call': functionCall,
                  'result': toolSummary,
                });
              }
            } catch (e, stackTrace) {
              LoggerService.error(
                'Tool execution failed: $e',
                error: e,
                stackTrace: stackTrace,
              );
              toolResults.add('Tool: $serviceName.$toolName\nError: $e');
            }
          }

          // Accumulate parts history
          if (partsHistory != null) {
            // If this is not the first iteration, we need to append to the existing history
            // However, the model returns the full history of the *current* turn's generation
            // We need to inject the tool results into this history for the next iteration
            // But here, we are preparing the final metadata for the ConversationMessage.

            // For the final message, we want the COMPLETE history of this interaction:
            // 1. Initial thought + tool call (from first iteration)
            // 2. Tool result (from execution)
            // 3. Subsequent thought + response (from next iteration)

            // Currently, 'partsHistory' only contains the parts from the *last* model response.
            // We need to maintain a running list of parts across iterations.
          }

          // Initialize running parts history if needed
          final runningPartsHistory =
              lastAssistantMetadata?['parts_history'] as List? ?? [];
          if (partsHistory != null) {
            runningPartsHistory.addAll(partsHistory);
          }

          // Inject tool results into the running history
          for (int i = 0; i < toolResults.length; i++) {
            runningPartsHistory.add({
              'type': 'tool_result',
              'text': toolResults[i],
              'is_included': true,
              // Link to the corresponding tool call if possible?
              // For now, just adding the result is enough for the UI to show it.
            });
          }

          if (toolResults.isNotEmpty) {
            final assistantMetadata = <String, dynamic>{
              'function_calls': functionCalls, // Keep for legacy
              'parts_history': runningPartsHistory, // Updated history
              'modelUsed':
                  response['modelUsed'] ??
                  getIt<ModelSelector>().currentModelConfig?.id,
            };

            if (toolCallsWithResults.isNotEmpty) {
              assistantMetadata['tool_calls_with_results'] =
                  toolCallsWithResults;
            }

            final assistantMessage = PromptMessage(
              role: PromptRole.assistant,
              content: textResponse ?? '',
              metadata: assistantMetadata,
            );
            lastAssistantMetadata = assistantMetadata;
            final currentModelConfig =
                generationContext.modelOverride ??
                getIt<ModelSelector>().currentModelConfig;
            if (currentModelConfig?.type == ModelType.openaiCompatible) {
              final toolMessages = toolCallsWithResults
                  .map(
                    (toolCall) => PromptMessage(
                      role: PromptRole.tool,
                      content: toolCall['result'] as String,
                      metadata: {'tool_call_id': toolCall['id']},
                    ),
                  )
                  .toList();

              currentMessages = [
                ...currentMessages,
                assistantMessage,
                ...toolMessages,
              ];
            } else {
              // Gemini: Use PromptRole.tool with function metadata for proper functionResponse format
              final toolMessages = <PromptMessage>[];
              for (int i = 0; i < toolResults.length; i++) {
                final functionCall = i < functionCalls.length
                    ? functionCalls[i]
                    : null;
                final toolCallResult = i < toolCallsWithResults.length
                    ? toolCallsWithResults[i]
                    : null;

                // Build metadata with function info and thought_signature
                final metadata = <String, dynamic>{};
                if (functionCall != null) {
                  metadata['function_name'] = functionCall['name'];
                  metadata['function_args'] = functionCall['args'];
                  // Preserve thought_signature for Gemini 3+ models
                  if (functionCall.containsKey('thoughtSignature')) {
                    metadata['thought_signature'] =
                        functionCall['thoughtSignature'];
                  }
                }
                // Also check toolCallResult for thought_signature (for error cases)
                if (toolCallResult != null &&
                    toolCallResult.containsKey('thought_signature')) {
                  metadata['thought_signature'] =
                      toolCallResult['thought_signature'];
                }

                toolMessages.add(
                  PromptMessage(
                    role: PromptRole.tool,
                    content: toolResults[i],
                    metadata: metadata.isNotEmpty ? metadata : null,
                  ),
                );
              }

              currentMessages = [
                ...currentMessages,
                assistantMessage,
                ...toolMessages,
              ];
            }

            final latestTools = resolveActiveTools();
            final newTools = _diffTools(
              previous: announcedToolKeys,
              current: latestTools,
            );
            if (newTools.isNotEmpty) {
              currentMessages = [
                ...currentMessages,
                PromptMessage(
                  role: PromptRole.system,
                  content: _buildDynamicToolDiscoveryMessage(
                    newTools,
                    isLocalModel: modelSelector
                            .currentModel?.usesNativeToolDeclarations ??
                        false,
                  ),
                ),
              ];
              announcedToolKeys.addAll(_toolKeys(newTools));
              cachedToolDeclarations = null; // Invalidate on tool changes
            }

            iteration++;
            continue;
          }
        }

        if (textResponse != null ||
            (partsHistory != null && partsHistory.isNotEmpty)) {
          if (textResponse != null && textResponse.isNotEmpty) {
            conversationParts.add(textResponse);
          }

          // Use the accumulated history
          final finalPartsHistory =
              lastAssistantMetadata?['parts_history'] as List? ?? [];
          if (partsHistory != null) {
            // If this was the final response (no more tools), add its parts
            finalPartsHistory.addAll(partsHistory);
          }

          final finalMetadata = <String, dynamic>{
            if (lastAssistantMetadata != null) ...lastAssistantMetadata,
            if (functionCalls != null) 'function_calls': functionCalls,
            'parts_history': finalPartsHistory,
            'modelUsed': textResponse != null || partsHistory != null
                ? (response['modelUsed'] ??
                      getIt<ModelSelector>().currentModelConfig?.id)
                : getIt<ModelSelector>().currentModelConfig?.id,
          };

          return ConversationAiResponse(
            content: conversationParts.join('\n\n'),
            metadata: finalMetadata,
          );
        }

        LoggerService.warning('AI returned empty response after tool calls');
        return const ConversationAiResponse(
          content: 'I was unable to generate a response. Please try again.',
        );
      }
    } on ConversationCancelledException {
      rethrow;
    } catch (e, stackTrace) {
      LoggerService.error(
        'Error during MCP tool execution: $e',
        error: e,
        stackTrace: stackTrace,
      );
      return const ConversationAiResponse(
        content:
            'I encountered an error while coordinating tools for this request. Please try again.',
        metadata: {'is_client_synthetic': true},
      );
    }
  }

  Set<String> _toolKeys(Map<String, List<McpTool>> toolsByService) {
    return {
      for (final entry in toolsByService.entries)
        for (final tool in entry.value) '${entry.key}::${tool.name}',
    };
  }

  Map<String, List<McpTool>> _diffTools({
    required Set<String> previous,
    required Map<String, List<McpTool>> current,
  }) {
    final diff = <String, List<McpTool>>{};
    for (final entry in current.entries) {
      final fresh = entry.value
          .where((tool) => !previous.contains('${entry.key}::${tool.name}'))
          .toList();
      if (fresh.isNotEmpty) {
        diff[entry.key] = fresh;
      }
    }
    return diff;
  }

  String _buildDynamicToolDiscoveryMessage(
    Map<String, List<McpTool>> newTools, {
    bool isLocalModel = false,
  }) {
    if (isLocalModel) {
      // Compact but informative for local models (Gemma) — include
      // descriptions so the model can make informed tool selections.
      final toolLines = newTools.values
          .expand((tools) => tools)
          .map((t) => '- ${t.name}: ${t.description ?? t.name}')
          .join('\n');
      return 'New tools available:\n$toolLines\nCall the appropriate tool if needed.';
    }
    final prompt = McpToolIntegrationService.buildMcpSystemPrompt(
      newTools,
      maxBudgetTokens: 16000,
      includeWrapperIntro: false,
    ).trim();
    return [
      'EXECUTE NOW: New tools are ready. Call the appropriate tool immediately to complete the user\'s request.',
      'Do NOT explain what tools are available. Do NOT describe what you will do. Call a tool NOW.',
      prompt,
    ].where((line) => line.isNotEmpty).join('\n\n');
  }

  /// Build a helpful error message for unrecognized tool calls.
  /// Similar to Linux's "command not found" helper that suggests similar commands.
  String _buildUnknownToolErrorMessage(
    String functionName,
    dynamic rawArgs,
    Map<String, List<McpTool>> activeTools,
  ) {
    final buffer = StringBuffer();
    buffer.writeln('ERROR: Unrecognized function "$functionName"');
    buffer.writeln();
    buffer.writeln(
      'You must call tools through the "call_tool" function with:',
    );
    buffer.writeln('  - service_name: The endpoint/service name');
    buffer.writeln('  - tool_name: The tool name within the service');
    buffer.writeln('  - params: Object containing the tool parameters');
    buffer.writeln();

    // Search for matching tools (command not found helper)
    final matches = <MapEntry<String, String>>[]; // (tool_name, service_name)
    for (final entry in activeTools.entries) {
      final serviceName = entry.key;
      for (final tool in entry.value) {
        if (tool.name == functionName ||
            tool.name.toLowerCase().contains(functionName.toLowerCase()) ||
            functionName.toLowerCase().contains(tool.name.toLowerCase())) {
          matches.add(MapEntry(tool.name, serviceName));
        }
      }
    }

    if (matches.isNotEmpty) {
      buffer.writeln('Did you mean to call one of these?');
      for (final match in matches) {
        buffer.writeln(
          '  call_tool({service_name: "${match.value}", tool_name: "${match.key}", params: {...}})',
        );
      }
    } else if (activeTools.isNotEmpty) {
      buffer.writeln('Available services: ${activeTools.keys.join(", ")}');
    }

    return buffer.toString();
  }

  Map<String, String>? _resolveDirectToolCall(
    String functionName,
    Map<String, List<McpTool>> activeTools,
  ) {
    final matches = <Map<String, String>>[];
    for (final entry in activeTools.entries) {
      for (final tool in entry.value) {
        if (tool.name == functionName) {
          matches.add({'service_name': entry.key, 'tool_name': tool.name});
        }
      }
    }

    if (matches.length == 1) {
      return matches.first;
    }
    return null;
  }
}
