import 'dart:async';

import 'package:file_picker/file_picker.dart';

import '../models/conversation.dart';
import '../models/mcp_endpoint.dart';
import '../models/model_type.dart';
import '../models/generation_context.dart';
import '../services/logger_service.dart';
import '../services/mcp_tool_integration_service.dart';
import '../services/model_selector.dart';
import '../services/models/local_mnn_model.dart';
import '../services/service_locator.dart';
import '../services/prompts/prompt_models.dart';
import '../services/prompts/system_prompt_builder.dart';
import '../services/prompts/registrations/chat_prompt_configuration.dart';
import 'conversation_settings_service.dart';
import 'prompts/prompt_configuration_service.dart';
import 'tools/tool_outcome.dart';

class ConversationCancelledException implements Exception {
  const ConversationCancelledException([
    this.message = 'Request cancelled by user',
  ]);

  final String message;

  @override
  String toString() => message;
}

class ConversationAiResponse {
  const ConversationAiResponse({required this.content, this.metadata});

  final String content;
  final Map<String, dynamic>? metadata;
}

typedef ToolExecutionCallback =
    Future<String> Function(
      String serviceName,
      String toolName,
      Map<String, dynamic> params,
      GenerationContext generationContext,
    );

typedef ActiveToolsProvider = Map<String, List<McpTool>> Function();

typedef CancellationCheck = bool Function();
typedef IterationsExhaustedHandler = Future<int?> Function(int exhaustedLimit);

class ConversationAiEngine {
  const ConversationAiEngine();

  /// Invalid-argument failures allowed per tool per turn before the tool is
  /// blocked (and one further attempt terminates the turn). Catches
  /// argument-variant retry loops that byte-identity dedupe cannot.
  static const int _maxInvalidArgumentFailuresPerTool = 3;

  /// Converts stored [ConversationMessage]s into [PromptMessage]s for model
  /// consumption. Handles role conversion for model mismatches, modelUsed
  /// metadata propagation, timestamp context, attachment loading, and tool
  /// result injection.
  ///
  /// Used by both conversation_chat_screen and immersive_note_screen.
  static Future<List<PromptMessage>> buildConversationMessages({
    required List<ConversationMessage> messages,
    required String? currentModelId,
    required Future<List<PlatformFile>> Function(ConversationMessage)
    loadAttachments,
  }) async {
    final conversationMessages = <PromptMessage>[];

    for (final message in messages) {
      // Filter out synthesized error messages
      if (message.metadata?['isSynthesized'] == true) {
        continue;
      }

      var role = message.type == MessageType.user
          ? PromptRole.user
          : PromptRole.assistant;
      var content = message.content;

      // Resolve modelUsed: prefer the DB column, fall back to metadata.
      // The DB column is always populated for saved messages; metadata may
      // or may not contain it depending on how the message was originally saved.
      final modelUsed =
          message.modelUsed ?? message.metadata?['modelUsed'] as String?;

      // If the message was generated by a different model, treat it as a user
      // message to avoid potential format/capability mismatches (e.g.
      // thoughtSignature). When modelUsed is null (legacy messages), we
      // cautiously treat it as a different model to avoid generation failures.
      if (role == PromptRole.assistant) {
        if (currentModelId != null &&
            (modelUsed == null || modelUsed != currentModelId)) {
          role = PromptRole.user;
          final modelLabel = modelUsed ?? 'an earlier model';
          content = '[Response from $modelLabel]:\n$content';
        }
      }

      // Prepend every user message with a timestamp context message.
      if (role == PromptRole.user) {
        final messageTimeContext = SystemPromptBuilder.formatTimestamp(
          message.timestamp,
        );
        final perMessageAddOn = PromptConfigurationService.instance.getValue(
          ChatPromptConfiguration.perMessageAddendumId,
        );
        final buffer = StringBuffer()
          ..write('Message created at: $messageTimeContext');
        if (perMessageAddOn != null && perMessageAddOn.trim().isNotEmpty) {
          buffer
            ..writeln()
            ..write(perMessageAddOn.trim());
        }
        conversationMessages.add(
          PromptMessage(role: PromptRole.user, content: buffer.toString()),
        );
      }

      final attachments = await loadAttachments(message);

      // Ensure modelUsed is in metadata so downstream model layers (e.g.
      // Gemini's isModelMatch) can read it.
      final effectiveMetadata = <String, dynamic>{
        ...?message.metadata,
        if (message.modelUsed != null && message.metadata?['modelUsed'] == null)
          'modelUsed': message.modelUsed,
      };

      final promptMessage = PromptMessage(
        role: role,
        content: content,
        attachments: attachments,
        metadata: effectiveMetadata.isNotEmpty ? effectiveMetadata : null,
      );

      conversationMessages.add(promptMessage);

      // Add tool results from assistant messages that kept their role
      if (role == PromptRole.assistant) {
        final toolCallsWithResults =
            message.metadata?['tool_calls_with_results'] as List?;
        if (toolCallsWithResults != null && toolCallsWithResults.isNotEmpty) {
          for (final entry in toolCallsWithResults) {
            final toolCallId = entry['id'];
            final toolResult = entry['result'] as String? ?? '';
            conversationMessages.add(
              PromptMessage(
                role: PromptRole.tool,
                content: toolResult,
                metadata: {
                  if (toolCallId != null) 'tool_call_id': toolCallId,
                  ...((entry is Map<String, dynamic>) ? entry : {}),
                },
              ),
            );
          }
        }
      }
    }

    return conversationMessages;
  }

  Future<ConversationAiResponse> generate({
    required PromptRequest request,
    required Map<String, List<McpTool>> activeTools,
    ActiveToolsProvider? activeToolsProvider,
    required bool enableTools,
    required ToolExecutionCallback executeTool,
    required CancellationCheck isCancelled,
    required GenerationContext generationContext,
    int? maxToolIterations,
    IterationsExhaustedHandler? onIterationsExhausted,
    void Function(String chunk)? onStreamChunk,
  }) async {
    if (isCancelled()) {
      throw const ConversationCancelledException();
    }

    // Always use the tool-enabled path to ensure consistent handling of parts_history
    // and other metadata, even if no tools are active.
    return _generateWithTools(
      request: request,
      activeTools: activeTools,
      activeToolsProvider: activeToolsProvider,
      executeTool: executeTool,
      isCancelled: isCancelled,
      generationContext: generationContext,
      maxToolIterations: maxToolIterations,
      onIterationsExhausted: onIterationsExhausted,
      onStreamChunk: onStreamChunk,
    );
  }

  /// Generate a response with tool-calling support.
  ///
  /// Tool descriptions reach the model through three complementary paths:
  ///
  /// 1. **System prompt text catalog** (`buildMcpSystemPrompt`) — built by the
  ///    caller (e.g. conversation_chat_screen) and embedded in the system
  ///    message. Skipped for models with [AIModel.usesNativeToolDeclarations].
  ///
  /// 2. **Native tool declarations** (`buildToolDeclarations`) — structured
  ///    schemas passed alongside the request. Cloud models get a single
  ///    `call_tool` wrapper; local models get individual per-tool declarations
  ///    for constrained decoding.
  ///
  /// 3. **Mid-conversation discovery** (`_buildDynamicToolDiscoveryMessage`) —
  ///    injected as a system message when new tools appear between iterations
  ///    (e.g. after a skill loads an MCP endpoint). Local models get a compact
  ///    list; cloud models get the full text catalog.
  Future<ConversationAiResponse> _generateWithTools({
    required PromptRequest request,
    required Map<String, List<McpTool>> activeTools,
    ActiveToolsProvider? activeToolsProvider,
    required ToolExecutionCallback executeTool,
    required CancellationCheck isCancelled,
    required GenerationContext generationContext,
    int? maxToolIterations,
    IterationsExhaustedHandler? onIterationsExhausted,
    void Function(String chunk)? onStreamChunk,
  }) async {
    try {
      final requestId = generationContext.ensureRequestId();
      if (isCancelled()) {
        throw const ConversationCancelledException();
      }

      var currentMessages = <PromptMessage>[
        request.systemMessage,
        ...request.contextMessages,
        ...request.conversationMessages,
      ];

      Map<String, List<McpTool>> resolveActiveTools() {
        final resolved = activeToolsProvider?.call() ?? activeTools;
        return {
          for (final entry in resolved.entries)
            entry.key: List<McpTool>.unmodifiable(entry.value),
        };
      }

      final modelSelector = getIt<ModelSelector>();
      var currentActiveTools = resolveActiveTools();
      final announcedToolKeys = _toolKeys(currentActiveTools);
      List<Map<String, dynamic>>? cachedToolDeclarations;

      LoggerService.info(
        'Starting conversation with ${currentActiveTools.length} tools',
        error: {'requestId': requestId},
      );

      int iterationLimit =
          maxToolIterations ??
          ConversationSettingsService.defaultMaxToolIterations;
      iterationLimit =
          iterationLimit < ConversationSettingsService.minToolIterations
          ? ConversationSettingsService.minToolIterations
          : (iterationLimit > ConversationSettingsService.maxToolIterationsCap
                ? ConversationSettingsService.maxToolIterationsCap
                : iterationLimit);
      var iteration = 0;
      final conversationParts = <String>[];
      Map<String, dynamic>? lastAssistantMetadata;
      // Cumulative parts across all iterations, used ONLY for the final
      // persisted message metadata. In-flight assistant messages carry only
      // their own iteration's slice; sharing (or copying) the cumulative list
      // into every iteration's message re-sends every prior tool call in
      // every model turn, ballooning the request superlinearly.
      final persistedPartsHistory = <dynamic>[];

      // Retry discipline + honest-failure bookkeeping for this turn.
      // Deterministic failures keyed by canonical call identity: a second
      // byte-equivalent call is not executed again. Tools whose failures are
      // never followed by a success of the same tool get deterministic
      // disclosure in the final message regardless of what the model claims.
      final deterministicFailures = <String, ToolOutcome>{};
      final unresolvedToolFailures = <String, Map<String, dynamic>>{};
      final succeededToolNames = <String>{};
      // Circuit breaker for argument-VARIANT loops, which byte-identity
      // dedupe cannot catch (a model mutating one detail per retry): after
      // N invalid_argument failures for one tool, the tool is blocked for
      // the turn; a further attempt terminates the turn immediately.
      final invalidArgFailuresByTool = <String, int>{};
      final invalidArgBlockedTools = <String>{};

      // Streaming-first for local models: stream with tool awareness.
      // If pure text, return fast. If tool calls detected, seed and enter
      // the tool loop for execution. Only applies without model override.
      final activeModel = generationContext.modelOverride == null
          ? modelSelector.currentModel
          : null;
      Map<String, dynamic>? streamingFirstResult;
      if (activeModel is LocalMnnModel &&
          activeModel.supportsStreaming &&
          onStreamChunk != null) {
        final toolDeclarations = getIt<ModelSelector>().buildToolDeclarations(
          currentActiveTools,
          generationContext: generationContext,
        );
        final result = await activeModel.generateStreamingWithTools(
          currentMessages,
          toolDeclarations,
          onChunk: (chunk) {
            if (isCancelled()) return;
            onStreamChunk(chunk);
          },
          generationContext: generationContext,
        );
        if (isCancelled()) throw const ConversationCancelledException();

        final calls = result['function_calls'] as List?;
        if (calls == null || calls.isEmpty) {
          // Pure text — fast streaming return
          return ConversationAiResponse(
            content: result['text'] as String? ?? '',
            metadata: {'modelUsed': activeModel.name},
          );
        }
        // Tool calls detected — store result and fall through to tool loop
        streamingFirstResult = result;
      }

      while (true) {
        if (iteration >= iterationLimit) {
          if (onIterationsExhausted != null) {
            final nextLimit = await onIterationsExhausted(iterationLimit);
            if (nextLimit == null) {
              throw const ConversationCancelledException(
                'Tool iteration limit reached and user aborted.',
              );
            }
            final sanitizedNext =
                nextLimit < ConversationSettingsService.minToolIterations
                ? ConversationSettingsService.minToolIterations
                : (nextLimit > ConversationSettingsService.maxToolIterationsCap
                      ? ConversationSettingsService.maxToolIterationsCap
                      : nextLimit);
            if (sanitizedNext <= iterationLimit) {
              LoggerService.warning(
                'Rejected iteration limit $nextLimit (must be greater than $iterationLimit)',
              );
              continue;
            }
            iterationLimit = sanitizedNext;
            continue;
          }

          LoggerService.warning(
            'MCP tool loop exceeded $iterationLimit iterations',
          );
          return ConversationAiResponse(
            content: [
              'I was unable to complete the request with the available tools. Please try again later.',
              if (unresolvedToolFailures.isNotEmpty)
                _buildToolFailureDisclosure(unresolvedToolFailures),
            ].join('\n\n'),
            metadata: {
              'isSynthesized': true,
              if (unresolvedToolFailures.isNotEmpty)
                'failed_tool_calls': unresolvedToolFailures.values.toList(),
            },
          );
        }

        if (isCancelled()) {
          throw const ConversationCancelledException();
        }

        LoggerService.debug('MCP iteration ${iteration + 1}/$iterationLimit');

        currentActiveTools = resolveActiveTools();

        // Use streaming-first result if available (first iteration only),
        // otherwise generate normally with cached tool declarations.
        final Map<String, dynamic> response;
        if (streamingFirstResult != null) {
          response = streamingFirstResult;
          streamingFirstResult = null;
        } else {
          cachedToolDeclarations ??= getIt<ModelSelector>()
              .buildToolDeclarations(
                currentActiveTools,
                generationContext: generationContext,
              );
          response = await getIt<ModelSelector>()
              .generateWithToolsAndMessages(
                currentMessages,
                cachedToolDeclarations,
                generationContext: generationContext,
              );
        }

        if (isCancelled()) {
          throw const ConversationCancelledException();
        }

        final textResponse = response['text'] as String?;
        final functionCalls = response['function_calls'] as List?;
        final partsHistory = response['parts_history'] as List?;

        if (functionCalls != null && functionCalls.isNotEmpty) {
          LoggerService.info(
            'AI requested ${functionCalls.length} tool call(s)',
          );

          // One record per function call — success, execution error, unknown
          // tool, or unparseable arguments — so every call is guaranteed a
          // paired response message downstream.
          final callRecords = <Map<String, dynamic>>[];

          for (int i = 0; i < functionCalls.length; i++) {
            if (isCancelled()) {
              throw const ConversationCancelledException();
            }

            final functionCall = functionCalls[i] as Map<String, dynamic>;
            final functionName = functionCall['name'] as String;
            final rawArgs = functionCall['args'];

            LoggerService.debug(
              'Processing function call',
              error: {'functionName': functionName, 'args': rawArgs},
            );

            String? serviceName;
            String? toolName;
            Map<String, dynamic>? params;

            if (functionName != 'call_tool') {
              final directTool = _resolveDirectToolCall(
                functionName,
                currentActiveTools,
              );
              if (directTool != null) {
                final parsedArgs =
                    McpToolIntegrationService.parseCallToolArguments(
                      rawArgs,
                      fallbackServiceName: directTool['service_name'],
                      fallbackToolName: directTool['tool_name'],
                      logErrors: false,
                    );
                serviceName =
                    (parsedArgs?['service_name'] as String?) ??
                    directTool['service_name']!;
                toolName =
                    (parsedArgs?['tool_name'] as String?) ??
                    directTool['tool_name']!;
                params =
                    parsedArgs?['params'] as Map<String, dynamic>? ??
                    (rawArgs is Map<String, dynamic>
                        ? Map<String, dynamic>.from(rawArgs)
                        : rawArgs is Map
                        ? rawArgs.map(
                            (key, value) => MapEntry(key.toString(), value),
                          )
                        : <String, dynamic>{});
              } else {
                // Model called a tool directly by name instead of using call_tool wrapper
                // Return an error with helpful guidance (like "command not found" helper)
                final errorMessage = _buildUnknownToolErrorMessage(
                  functionName,
                  rawArgs,
                  activeTools,
                );

                LoggerService.warning(
                  'Unknown function call: $functionName, returning error to LLM',
                );

                final errorResult = 'Error: $errorMessage';
                conversationParts.add(
                  '[Tool error: Unknown function "$functionName"]',
                );
                callRecords.add({
                  'function_call': functionCall,
                  'result': errorResult,
                  'dispatched': false,
                  'id':
                      functionCall['id'] as String? ??
                      't_err_${DateTime.now().millisecondsSinceEpoch.toRadixString(36)}_$i',
                });

                continue;
              }
            } else {
              final parsedArgs =
                  McpToolIntegrationService.parseCallToolArguments(rawArgs);
              if (parsedArgs == null) {
                LoggerService.error(
                  'Failed to parse call_tool arguments',
                  error: {'args': rawArgs},
                );
                // Record a paired error response anyway — a functionCall with
                // no functionResponse violates the wire contract and leaves
                // the model with no feedback to correct itself.
                conversationParts.add(
                  '[Tool error: Invalid call_tool arguments]',
                );
                callRecords.add({
                  'function_call': functionCall,
                  'result':
                      'Error: Could not parse call_tool arguments. Expected '
                      '{"service_name": "...", "tool_name": "...", '
                      '"params": {...}} with every tool argument inside '
                      '"params".',
                  'dispatched': false,
                  'id':
                      functionCall['id'] as String? ??
                      't_err_${DateTime.now().millisecondsSinceEpoch.toRadixString(36)}_$i',
                });
                continue;
              }

              serviceName = parsedArgs['service_name'] as String;
              toolName = parsedArgs['tool_name'] as String;
              params = parsedArgs['params'] as Map<String, dynamic>;
            }

            LoggerService.info('Executing: $serviceName.$toolName');
            LoggerService.debug('Tool parameters', error: params);

            final qualifiedName = '$serviceName.$toolName';
            final callKey = canonicalToolCallKey(
              serviceName: serviceName,
              toolName: toolName,
              params: params,
            );

            if (invalidArgBlockedTools.contains(qualifiedName)) {
              // The model called a blocked tool AGAIN after the terminal
              // directive — end the turn now with a harness-synthesized
              // honest failure instead of burning the remaining iterations.
              LoggerService.warning(
                'Circuit breaker: terminating turn after repeated invalid '
                'calls to $qualifiedName',
              );
              return ConversationAiResponse(
                content: [
                  ...conversationParts,
                  'I was unable to complete the request: $qualifiedName was '
                      'called repeatedly with invalid arguments.',
                  if (unresolvedToolFailures.isNotEmpty)
                    _buildToolFailureDisclosure(unresolvedToolFailures),
                ].join('\n\n'),
                metadata: {
                  'isSynthesized': true,
                  if (unresolvedToolFailures.isNotEmpty)
                    'failed_tool_calls': unresolvedToolFailures.values
                        .toList(),
                },
              );
            }

            String result;
            ToolOutcome? failure;
            final priorFailure = deterministicFailures[callKey];
            final invalidArgStrikes =
                invalidArgFailuresByTool[qualifiedName] ?? 0;
            if (priorFailure == null &&
                invalidArgStrikes >= _maxInvalidArgumentFailuresPerTool) {
              // Third strike: stop executing this tool for the rest of the
              // turn, regardless of how the arguments vary.
              invalidArgBlockedTools.add(qualifiedName);
              failure = ToolOutcome.failure(
                code: ToolOutcome.codeInvalidArgument,
                message:
                    '$qualifiedName has failed $invalidArgStrikes times with '
                    'invalid arguments this turn and is now blocked; the '
                    'call was NOT executed. Do NOT call it again. Tell the '
                    'user the operation could not be completed.',
              );
              result = failure.serialize();
            } else if (priorFailure != null) {
              // Second byte-equivalent call after a deterministic failure —
              // do NOT execute it again; return an escalated directive.
              LoggerService.warning(
                'Skipping repeated failing call to $qualifiedName',
              );
              failure = ToolOutcome.failure(
                code: priorFailure.code,
                message: priorFailure.isUserDenied
                    ? 'The user already declined this exact action; it was '
                          'NOT retried. Do not ask again — adjust your plan '
                          'or finish, and tell the user the action was not '
                          'performed.'
                    : 'This exact call to $qualifiedName already failed and '
                          'was NOT executed again. Previous error: '
                          '${priorFailure.message} Change the arguments, use '
                          'a different tool, or stop and report the failure '
                          'to the user. Never claim this operation '
                          'succeeded.',
              );
              result = failure.serialize();
            } else {
              try {
                result = await executeTool(
                  serviceName,
                  toolName,
                  params,
                  generationContext,
                );
              } catch (e, stackTrace) {
                LoggerService.error(
                  'Tool execution failed: $e',
                  error: e,
                  stackTrace: stackTrace,
                );
                result = ToolOutcome.fromException(
                  qualifiedName,
                  e,
                ).serialize();
              }
              failure = ToolOutcome.tryParseFailure(result);
            }

            if (failure != null) {
              if (!failure.retryable) {
                deterministicFailures[callKey] = failure;
              }
              if (failure.isInvalidArgument) {
                invalidArgFailuresByTool[qualifiedName] =
                    (invalidArgFailuresByTool[qualifiedName] ?? 0) + 1;
              }
              var summary = failure.message;
              if (summary.length > 300) {
                summary = '${summary.substring(0, 300)}…';
              }
              // Keyed by call identity, not tool name: a success against a
              // DIFFERENT target must not erase this call's disclosure.
              unresolvedToolFailures[callKey] = {
                'tool': qualifiedName,
                'code': failure.code,
                'message': summary,
              };
              conversationParts.add('[Tool failed: $qualifiedName]');
            } else {
              succeededToolNames.add(qualifiedName);
              // A success clears the exact same call's failure (e.g. a
              // transport retry that went through), and this tool's
              // invalid_argument failures (the model corrected its
              // arguments and the corrected call succeeded). Failures of
              // other calls to the same tool — different targets — stay
              // disclosed.
              unresolvedToolFailures.removeWhere(
                (key, info) =>
                    key == callKey ||
                    (info['tool'] == qualifiedName &&
                        info['code'] == ToolOutcome.codeInvalidArgument),
              );
              deterministicFailures.remove(callKey);
              invalidArgFailuresByTool.remove(qualifiedName);
              invalidArgBlockedTools.remove(qualifiedName);
              conversationParts.add('[Tool executed: $qualifiedName]');
            }

            final toolSummary = failure != null
                ? 'Tool: $qualifiedName\nError: $result'
                : 'Tool: $qualifiedName\nResult: $result';
            callRecords.add({
              'function_call': functionCall,
              'result': toolSummary,
              'dispatched': true,
              'id':
                  functionCall['id'] as String? ??
                  't_${DateTime.now().millisecondsSinceEpoch.toRadixString(36)}_${toolName.length > 10 ? toolName.substring(0, 10) : toolName}_$i',
            });
          }

          // This iteration's own parts (the model's response for THIS call
          // only). The cumulative history lives in [persistedPartsHistory]
          // and is attached exclusively to the final persisted metadata, so
          // in-flight assistant messages never re-send prior iterations'
          // tool calls.
          final iterationPartsHistory = <dynamic>[...?partsHistory];
          persistedPartsHistory.addAll(iterationPartsHistory);

          // Tool results go into the persisted (UI-facing) history only; the
          // wire formats replay them via PromptRole.tool messages below.
          for (final record in callRecords) {
            persistedPartsHistory.add({
              'type': 'tool_result',
              'text': record['result'],
              'is_included': true,
            });
          }

          if (callRecords.isNotEmpty) {
            final currentModelConfig =
                generationContext.modelOverride ??
                getIt<ModelSelector>().currentModelConfig;
            final isOpenAiCompatible =
                currentModelConfig?.type == ModelType.openaiCompatible;

            final toolCallsWithResults = <Map<String, dynamic>>[
              for (final record in callRecords)
                if (isOpenAiCompatible)
                  {
                    'id': record['id'],
                    'function_call': record['function_call'],
                    'result': record['result'],
                  }
                else if (record['dispatched'] != true)
                  // Gemini legacy shape, kept for undispatched calls only
                  // (unknown tool / unparseable args) as before.
                  {
                    'function_name':
                        (record['function_call'] as Map)['name'],
                    'function_args':
                        (record['function_call'] as Map)['args'],
                    'result': record['result'],
                    if ((record['function_call'] as Map).containsKey(
                      'thoughtSignature',
                    ))
                      'thought_signature':
                          (record['function_call'] as Map)['thoughtSignature'],
                  },
            ];

            final assistantMetadata = <String, dynamic>{
              'function_calls': functionCalls, // Keep for legacy
              // This iteration's parts only — never the cumulative history.
              'parts_history': iterationPartsHistory,
              'modelUsed':
                  response['modelUsed'] ??
                  getIt<ModelSelector>().currentModelConfig?.id,
            };

            if (toolCallsWithResults.isNotEmpty) {
              assistantMetadata['tool_calls_with_results'] =
                  toolCallsWithResults;
            }

            final assistantMessage = PromptMessage(
              role: PromptRole.assistant,
              content: textResponse ?? '',
              metadata: assistantMetadata,
            );
            lastAssistantMetadata = assistantMetadata;

            // Exactly one tool message per function call, in call order —
            // including error and unparseable-argument outcomes.
            final toolMessages = <PromptMessage>[
              for (final record in callRecords)
                if (isOpenAiCompatible)
                  PromptMessage(
                    role: PromptRole.tool,
                    content: record['result'] as String,
                    metadata: {'tool_call_id': record['id']},
                  )
                else
                  // Gemini/local: function metadata for proper
                  // functionResponse pairing.
                  PromptMessage(
                    role: PromptRole.tool,
                    content: record['result'] as String,
                    metadata: {
                      'function_name':
                          (record['function_call'] as Map)['name'],
                      'function_args':
                          (record['function_call'] as Map)['args'],
                      if ((record['function_call'] as Map).containsKey(
                        'thoughtSignature',
                      ))
                        'thought_signature': (record['function_call']
                            as Map)['thoughtSignature'],
                    },
                  ),
            ];

            currentMessages = [
              ...currentMessages,
              assistantMessage,
              ...toolMessages,
            ];

            final latestTools = resolveActiveTools();
            final newTools = _diffTools(
              previous: announcedToolKeys,
              current: latestTools,
            );
            if (newTools.isNotEmpty) {
              currentMessages = [
                ...currentMessages,
                PromptMessage(
                  role: PromptRole.system,
                  content: _buildDynamicToolDiscoveryMessage(
                    newTools,
                    isLocalModel: modelSelector
                            .currentModel?.usesNativeToolDeclarations ??
                        false,
                  ),
                ),
              ];
              announcedToolKeys.addAll(_toolKeys(newTools));
              cachedToolDeclarations = null; // Invalidate on tool changes
            }

            iteration++;
            continue;
          }
        }

        if (textResponse != null ||
            (partsHistory != null && partsHistory.isNotEmpty)) {
          if (textResponse != null && textResponse.isNotEmpty) {
            conversationParts.add(textResponse);
          }

          // The persisted metadata carries the COMPLETE history of this
          // interaction (every iteration's parts, tool results, and the
          // final response's parts) as a fresh list that is never aliased
          // to any in-flight message's metadata.
          final finalPartsHistory = <dynamic>[
            ...persistedPartsHistory,
            ...?partsHistory,
          ];

          final finalMetadata = <String, dynamic>{
            if (lastAssistantMetadata != null) ...lastAssistantMetadata,
            if (functionCalls != null) 'function_calls': functionCalls,
            'parts_history': finalPartsHistory,
            'modelUsed': textResponse != null || partsHistory != null
                ? (response['modelUsed'] ??
                      getIt<ModelSelector>().currentModelConfig?.id)
                : getIt<ModelSelector>().currentModelConfig?.id,
          };

          // Harness-owned honest-failure disclosure: the engine knows every
          // call's outcome, so unresolved failures are disclosed
          // deterministically — the model's own claims cannot override this.
          if (unresolvedToolFailures.isNotEmpty) {
            conversationParts.add(
              _buildToolFailureDisclosure(unresolvedToolFailures),
            );
            finalMetadata['failed_tool_calls'] = unresolvedToolFailures.values
                .toList();
            if (succeededToolNames.isNotEmpty) {
              finalMetadata['succeeded_tool_calls'] = succeededToolNames
                  .toList();
            }
          }

          return ConversationAiResponse(
            content: conversationParts.join('\n\n'),
            metadata: finalMetadata,
          );
        }

        LoggerService.warning('AI returned empty response after tool calls');
        return ConversationAiResponse(
          content: [
            'I was unable to generate a response. Please try again.',
            if (unresolvedToolFailures.isNotEmpty)
              _buildToolFailureDisclosure(unresolvedToolFailures),
          ].join('\n\n'),
          metadata: {
            if (unresolvedToolFailures.isNotEmpty)
              'failed_tool_calls': unresolvedToolFailures.values.toList(),
          },
        );
      }
    } on ConversationCancelledException {
      rethrow;
    } catch (e, stackTrace) {
      LoggerService.error(
        'Error during MCP tool execution: $e',
        error: e,
        stackTrace: stackTrace,
      );
      return const ConversationAiResponse(
        content:
            'I encountered an error while coordinating tools for this request. Please try again.',
        metadata: {'is_client_synthetic': true},
      );
    }
  }

  /// Deterministic user-facing report of tool calls that never succeeded in
  /// this turn. Appended by the harness so a model claiming success cannot
  /// hide a failed operation. (Hardcoded English, consistent with the
  /// engine's other synthesized messages.)
  String _buildToolFailureDisclosure(
    Map<String, Map<String, dynamic>> failures,
  ) {
    final lines = failures.values.map((failure) {
      final label = failure['code'] == ToolOutcome.codeUserDenied
          ? 'declined by you'
          : 'failed';
      return '- ${failure['tool']} ($label): ${failure['message']}';
    });
    return '⚠️ Tool execution report: the following operations did NOT '
        'complete, so their changes were not applied. If the answer above '
        'claims otherwise, disregard that claim.\n${lines.join('\n')}';
  }

  Set<String> _toolKeys(Map<String, List<McpTool>> toolsByService) {
    return {
      for (final entry in toolsByService.entries)
        for (final tool in entry.value) '${entry.key}::${tool.name}',
    };
  }

  Map<String, List<McpTool>> _diffTools({
    required Set<String> previous,
    required Map<String, List<McpTool>> current,
  }) {
    final diff = <String, List<McpTool>>{};
    for (final entry in current.entries) {
      final fresh = entry.value
          .where((tool) => !previous.contains('${entry.key}::${tool.name}'))
          .toList();
      if (fresh.isNotEmpty) {
        diff[entry.key] = fresh;
      }
    }
    return diff;
  }

  String _buildDynamicToolDiscoveryMessage(
    Map<String, List<McpTool>> newTools, {
    bool isLocalModel = false,
  }) {
    if (isLocalModel) {
      // Compact but informative for local models (Gemma) — include
      // descriptions so the model can make informed tool selections.
      final toolLines = newTools.values
          .expand((tools) => tools)
          .map((t) => '- ${t.name}: ${t.description ?? t.name}')
          .join('\n');
      return 'New tools available:\n$toolLines\nCall the appropriate tool if needed.';
    }
    final prompt = McpToolIntegrationService.buildMcpSystemPrompt(
      newTools,
      maxBudgetTokens: 16000,
      includeWrapperIntro: false,
    ).trim();
    return [
      'EXECUTE NOW: New tools are ready. Call the appropriate tool immediately to complete the user\'s request.',
      'Do NOT explain what tools are available. Do NOT describe what you will do. Call a tool NOW.',
      'These tools have their own function declarations — call them DIRECTLY '
          'by name (arguments are validated as you write them); do not wrap '
          'them in call_tool.',
      prompt,
    ].where((line) => line.isNotEmpty).join('\n\n');
  }

  /// Build a helpful error message for unrecognized tool calls.
  /// Similar to Linux's "command not found" helper that suggests similar commands.
  String _buildUnknownToolErrorMessage(
    String functionName,
    dynamic rawArgs,
    Map<String, List<McpTool>> activeTools,
  ) {
    final buffer = StringBuffer();
    buffer.writeln('ERROR: Unrecognized function "$functionName"');
    buffer.writeln();
    buffer.writeln(
      'Call tools DIRECTLY by their declared function name when a '
      'declaration exists. For tools without their own declaration, use '
      '"call_tool" with:',
    );
    buffer.writeln('  - service_name: The endpoint/service name');
    buffer.writeln('  - tool_name: The tool name within the service');
    buffer.writeln('  - params: Object containing the tool parameters');
    buffer.writeln();

    // Search for matching tools (command not found helper)
    final matches = <MapEntry<String, String>>[]; // (tool_name, service_name)
    for (final entry in activeTools.entries) {
      final serviceName = entry.key;
      for (final tool in entry.value) {
        if (tool.name == functionName ||
            tool.name.toLowerCase().contains(functionName.toLowerCase()) ||
            functionName.toLowerCase().contains(tool.name.toLowerCase())) {
          matches.add(MapEntry(tool.name, serviceName));
        }
      }
    }

    if (matches.isNotEmpty) {
      buffer.writeln('Did you mean to call one of these?');
      for (final match in matches) {
        buffer.writeln(
          '  ${match.key}({...}) — or call_tool({service_name: '
          '"${match.value}", tool_name: "${match.key}", params: {...}})',
        );
      }
    } else if (activeTools.isNotEmpty) {
      buffer.writeln('Available services: ${activeTools.keys.join(", ")}');
    }

    return buffer.toString();
  }

  Map<String, String>? _resolveDirectToolCall(
    String functionName,
    Map<String, List<McpTool>> activeTools,
  ) {
    final matches = <Map<String, String>>[];
    for (final entry in activeTools.entries) {
      for (final tool in entry.value) {
        if (tool.name == functionName) {
          matches.add({'service_name': entry.key, 'tool_name': tool.name});
        }
      }
    }

    if (matches.length == 1) {
      return matches.first;
    }
    return null;
  }
}
