// Mocks generated by Mockito 5.4.6 from annotations
// in note_synapse/test/services/agent_service_subtask_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:file_picker/file_picker.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:note_synapse/models/app_revision.dart' as _i26;
import 'package:note_synapse/models/attachment.dart' as _i21;
import 'package:note_synapse/models/context_node.dart' as _i2;
import 'package:note_synapse/models/conversation.dart' as _i27;
import 'package:note_synapse/models/conversation_attachment.dart' as _i28;
import 'package:note_synapse/models/dedup_rule.dart' as _i18;
import 'package:note_synapse/models/filter.dart' as _i24;
import 'package:note_synapse/models/generation_context.dart' as _i13;
import 'package:note_synapse/models/mcp_endpoint.dart' as _i15;
import 'package:note_synapse/models/model_config.dart' as _i8;
import 'package:note_synapse/models/model_type.dart' as _i11;
import 'package:note_synapse/models/note.dart' as _i17;
import 'package:note_synapse/models/note_annotation.dart' as _i20;
import 'package:note_synapse/models/relationship.dart' as _i23;
import 'package:note_synapse/models/tag.dart' as _i22;
import 'package:note_synapse/models/task_result_storage.dart' as _i3;
import 'package:note_synapse/models/user_app.dart' as _i25;
import 'package:note_synapse/models/workflow_binding_row.dart' as _i29;
import 'package:note_synapse/providers/app_provider.dart' as _i10;
import 'package:note_synapse/services/ai_service.dart' as _i16;
import 'package:note_synapse/services/context_manager_service.dart' as _i5;
import 'package:note_synapse/services/database_service.dart' as _i19;
import 'package:note_synapse/services/model_selector.dart' as _i9;
import 'package:note_synapse/services/prompts/prompt_models.dart' as _i14;
import 'package:sqflite/sqflite.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeContextNode_0 extends _i1.SmartFake implements _i2.ContextNode {
  _FakeContextNode_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskResultStorage_1 extends _i1.SmartFake
    implements _i3.TaskResultStorage {
  _FakeTaskResultStorage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_2 extends _i1.SmartFake implements _i4.Database {
  _FakeDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContextManagerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockContextManagerService extends _i1.Mock
    implements _i5.ContextManagerService {
  MockContextManagerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get findingsCount =>
      (super.noSuchMethod(Invocation.getter(#findingsCount), returnValue: 0)
          as int);

  @override
  _i6.Future<int> getModelContextBudget() =>
      (super.noSuchMethod(
            Invocation.method(#getModelContextBudget, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i2.ContextNode> createRootContext({
    required String? objective,
    List<String>? allowedTools = const [],
    int? maxTokens,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRootContext, [], {
              #objective: objective,
              #allowedTools: allowedTools,
              #maxTokens: maxTokens,
            }),
            returnValue: _i6.Future<_i2.ContextNode>.value(
              _FakeContextNode_0(
                this,
                Invocation.method(#createRootContext, [], {
                  #objective: objective,
                  #allowedTools: allowedTools,
                  #maxTokens: maxTokens,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ContextNode>);

  @override
  _i2.ContextNode createChildContext({
    required _i2.ContextNode? parent,
    required String? objective,
    List<String>? allowedTools,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChildContext, [], {
              #parent: parent,
              #objective: objective,
              #allowedTools: allowedTools,
            }),
            returnValue: _FakeContextNode_0(
              this,
              Invocation.method(#createChildContext, [], {
                #parent: parent,
                #objective: objective,
                #allowedTools: allowedTools,
              }),
            ),
          )
          as _i2.ContextNode);

  @override
  void setActiveContext(_i2.ContextNode? context) => super.noSuchMethod(
    Invocation.method(#setActiveContext, [context]),
    returnValueForMissingStub: null,
  );

  @override
  String buildContextForNode(
    _i2.ContextNode? node, {
    int? tocThreshold = 1000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildContextForNode,
              [node],
              {#tocThreshold: tocThreshold},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #buildContextForNode,
                [node],
                {#tocThreshold: tocThreshold},
              ),
            ),
          )
          as String);

  @override
  String buildContextForSubtask(_i2.ContextNode? node) =>
      (super.noSuchMethod(
            Invocation.method(#buildContextForSubtask, [node]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#buildContextForSubtask, [node]),
            ),
          )
          as String);

  @override
  String buildContextForResearchTask(
    _i2.ContextNode? node, {
    List<String>? dependencyResults = const [],
    List<_i5.DependencyInfo>? structuredDependencies = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildContextForResearchTask,
              [node],
              {
                #dependencyResults: dependencyResults,
                #structuredDependencies: structuredDependencies,
              },
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #buildContextForResearchTask,
                [node],
                {
                  #dependencyResults: dependencyResults,
                  #structuredDependencies: structuredDependencies,
                },
              ),
            ),
          )
          as String);

  @override
  _i6.Future<void> compactNodeContext(_i2.ContextNode? node) =>
      (super.noSuchMethod(
            Invocation.method(#compactNodeContext, [node]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> generateFinalSummary(
    _i2.ContextNode? node, {
    List<String>? consumingTaskDescriptions = const [],
    _i8.ModelConfig? modelOverride,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFinalSummary,
              [node],
              {
                #consumingTaskDescriptions: consumingTaskDescriptions,
                #modelOverride: modelOverride,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateFinalSummary,
                  [node],
                  {
                    #consumingTaskDescriptions: consumingTaskDescriptions,
                    #modelOverride: modelOverride,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  void addLoadedSkill(String? noteId, String? content) => super.noSuchMethod(
    Invocation.method(#addLoadedSkill, [noteId, content]),
    returnValueForMissingStub: null,
  );

  @override
  void markContextFailed(_i2.ContextNode? node, String? error) =>
      super.noSuchMethod(
        Invocation.method(#markContextFailed, [node, error]),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> checkAndCompact(_i2.ContextNode? node) =>
      (super.noSuchMethod(
            Invocation.method(#checkAndCompact, [node]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addFindings(List<Map<String, dynamic>>? findings) => super.noSuchMethod(
    Invocation.method(#addFindings, [findings]),
    returnValueForMissingStub: null,
  );

  @override
  String buildSynthesisContext(
    _i2.ContextNode? node, {
    List<_i5.DependencyInfo>? structuredDependencies = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildSynthesisContext,
              [node],
              {#structuredDependencies: structuredDependencies},
            ),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(
                #buildSynthesisContext,
                [node],
                {#structuredDependencies: structuredDependencies},
              ),
            ),
          )
          as String);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  _i2.ContextNode? getContext(String? id) =>
      (super.noSuchMethod(Invocation.method(#getContext, [id]))
          as _i2.ContextNode?);

  @override
  void importSnapshot(Map<String, dynamic>? snapshot) => super.noSuchMethod(
    Invocation.method(#importSnapshot, [snapshot]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.TaskResultStorage generateTocFromResult(
    String? taskId,
    String? goal,
    String? result,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateTocFromResult, [taskId, goal, result]),
            returnValue: _FakeTaskResultStorage_1(
              this,
              Invocation.method(#generateTocFromResult, [taskId, goal, result]),
            ),
          )
          as _i3.TaskResultStorage);
}

/// A class which mocks [ModelSelector].
///
/// See the documentation for Mockito's code generation for more information.
class MockModelSelector extends _i1.Mock implements _i9.ModelSelector {
  MockModelSelector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize(_i10.AppProvider? appProvider) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [appProvider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> switchToModel(_i8.ModelConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#switchToModel, [config]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i11.ModelType> getAvailableModels() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableModels, []),
            returnValue: <_i11.ModelType>[],
          )
          as List<_i11.ModelType>);

  @override
  _i6.Future<String> generateWithAttachments(
    String? prompt,
    List<_i12.PlatformFile>? attachedFiles, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateWithAttachments,
              [prompt, attachedFiles],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateWithAttachments,
                  [prompt, attachedFiles],
                  {
                    #temperature: temperature,
                    #topK: topK,
                    #topP: topP,
                    #maxOutputTokens: maxOutputTokens,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> generateWithMessages(
    List<_i14.PromptMessage>? messages, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateWithMessages,
              [messages],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateWithMessages,
                  [messages],
                  {
                    #temperature: temperature,
                    #topK: topK,
                    #topP: topP,
                    #maxOutputTokens: maxOutputTokens,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> generateFromPrompt(
    _i14.PromptRequest? request, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFromPrompt,
              [request],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateFromPrompt,
                  [request],
                  {
                    #temperature: temperature,
                    #topK: topK,
                    #topP: topP,
                    #maxOutputTokens: maxOutputTokens,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<Map<String, dynamic>>> generateFromPromptMultiPart(
    _i14.PromptRequest? request, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateFromPromptMultiPart,
              [request],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>> generateWithTools(
    String? prompt,
    List<_i12.PlatformFile>? attachedFiles,
    List<Map<String, dynamic>>? tools, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateWithTools,
              [prompt, attachedFiles, tools],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  List<Map<String, dynamic>> buildToolDeclarations(
    Map<String, List<_i15.McpTool>>? toolsByEndpoint, {
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildToolDeclarations,
              [toolsByEndpoint],
              {#generationContext: generationContext},
            ),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> generateWithToolsAndMessages(
    List<_i14.PromptMessage>? messages,
    List<Map<String, dynamic>>? tools, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateWithToolsAndMessages,
              [messages, tools],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  String? checkLocalModelConstraints(
    List<_i14.PromptMessage>? messages,
    _i8.ModelConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#checkLocalModelConstraints, [messages, config]),
          )
          as String?);

  @override
  _i6.Future<_i8.ModelConfig?> getModelByHint(
    List<String>? hints, {
    _i8.ModelConfig? currentOverride,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getModelByHint,
              [hints],
              {#currentOverride: currentOverride},
            ),
            returnValue: _i6.Future<_i8.ModelConfig?>.value(),
          )
          as _i6.Future<_i8.ModelConfig?>);

  @override
  _i6.Future<_i8.ModelConfig?> selectModelByPreference(
    Set<String>? requiredCaps,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectModelByPreference, [requiredCaps]),
            returnValue: _i6.Future<_i8.ModelConfig?>.value(),
          )
          as _i6.Future<_i8.ModelConfig?>);
}

/// A class which mocks [AIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAIService extends _i1.Mock implements _i16.AIService {
  MockAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize(_i10.AppProvider? appProvider) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [appProvider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> executePrompt(
    _i14.PromptRequest? request, {
    double? temperature,
    int? topK,
    double? topP,
    int? maxOutputTokens,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executePrompt,
              [request],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #maxOutputTokens: maxOutputTokens,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #executePrompt,
                  [request],
                  {
                    #temperature: temperature,
                    #topK: topK,
                    #topP: topP,
                    #maxOutputTokens: maxOutputTokens,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> transformNote(
    _i17.Note? note,
    String? transformationPrompt, {
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformNote,
              [note, transformationPrompt],
              {
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #transformNote,
                  [note, transformationPrompt],
                  {
                    #attachedFiles: attachedFiles,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> transformBlock(
    String? blockContent,
    String? instruction, {
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformBlock,
              [blockContent, instruction],
              {#generationContext: generationContext},
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #transformBlock,
                  [blockContent, instruction],
                  {#generationContext: generationContext},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> generateWithAttachments(
    String? prompt,
    List<_i12.PlatformFile>? attachedFiles, {
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateWithAttachments,
              [prompt, attachedFiles],
              {#generationContext: generationContext},
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateWithAttachments,
                  [prompt, attachedFiles],
                  {#generationContext: generationContext},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i17.Note>> createNewNotes(
    String? prompt,
    List<_i17.Note>? contextNotes, {
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createNewNotes,
              [prompt, contextNotes],
              {
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<String> transcribeAudio(String? audioFilePath) =>
      (super.noSuchMethod(
            Invocation.method(#transcribeAudio, [audioFilePath]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#transcribeAudio, [audioFilePath]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> summarizeAudio(String? audioFilePath, {String? context}) =>
      (super.noSuchMethod(
            Invocation.method(
              #summarizeAudio,
              [audioFilePath],
              {#context: context},
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #summarizeAudio,
                  [audioFilePath],
                  {#context: context},
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<Map<String, dynamic>> extractContentFromText(
    String? text,
    String? contentType,
    String? title,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#extractContentFromText, [
              text,
              contentType,
              title,
            ]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> extractContentFromImage(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#extractContentFromImage, [imagePath]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> extractContentFromPdf(String? pdfPath) =>
      (super.noSuchMethod(
            Invocation.method(#extractContentFromPdf, [pdfPath]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i18.DedupRule>> suggestDedupRules(
    List<String>? tagNames, {
    List<String>? protectedTags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #suggestDedupRules,
              [tagNames],
              {#protectedTags: protectedTags},
            ),
            returnValue: _i6.Future<List<_i18.DedupRule>>.value(
              <_i18.DedupRule>[],
            ),
          )
          as _i6.Future<List<_i18.DedupRule>>);

  @override
  _i6.Future<String> generateApp(
    String? prompt, {
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateApp,
              [prompt],
              {
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #generateApp,
                  [prompt],
                  {
                    #attachedFiles: attachedFiles,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> chatAI(
    String? prompt, {
    double? temperature,
    int? topK,
    double? topP,
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
    List<String>? modelHint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #chatAI,
              [prompt],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
                #modelHint: modelHint,
              },
            ),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #chatAI,
                  [prompt],
                  {
                    #temperature: temperature,
                    #topK: topK,
                    #topP: topP,
                    #attachedFiles: attachedFiles,
                    #generationContext: generationContext,
                    #modelHint: modelHint,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<Map<String, dynamic>>> chatAIMultiPart(
    String? prompt, {
    double? temperature,
    int? topK,
    double? topP,
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
    List<String>? modelHint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #chatAIMultiPart,
              [prompt],
              {
                #temperature: temperature,
                #topK: topK,
                #topP: topP,
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
                #modelHint: modelHint,
              },
            ),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i19.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i4.Database>.value(
              _FakeDatabase_2(this, Invocation.getter(#database)),
            ),
          )
          as _i6.Future<_i4.Database>);

  @override
  _i6.Future<void> insertConversationMessageMappingsBatch(
    String? conversationId,
    List<String>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessageMappingsBatch, [
              conversationId,
              messageIds,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> validateConversationNotes(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#validateConversationNotes, [conversationId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<String> insertNote(_i17.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#insertNote, [note]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertNote, [note]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i17.Note>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<void> cleanupInvalidNoteReferences() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupInvalidNoteReferences, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i17.Note>> getNotesByArchiveStatus({bool? isArchived}) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByArchiveStatus, [], {
              #isArchived: isArchived,
            }),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<List<_i17.Note>> getPinnedNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedNotes, []),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<List<_i17.Note>> getArchivedNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedNotes, []),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<_i17.Note?> getNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNote, [id]),
            returnValue: _i6.Future<_i17.Note?>.value(),
          )
          as _i6.Future<_i17.Note?>);

  @override
  _i6.Future<List<_i17.Note>> getNotesByIds(List<String>? noteIds) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByIds, [noteIds]),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<List<_i17.Note>> getNotesByTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByTag, [tagName]),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<void> updateNote(_i17.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateAttachmentAIContext(
    String? noteId,
    String? filePath,
    bool? include,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttachmentAIContext, [
              noteId,
              filePath,
              include,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateAttachmentMetadata(
    String? attachmentId,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttachmentMetadata, [
              attachmentId,
              metadata,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateNoteMetadata(
    String? noteId,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteMetadata, [noteId, metadata]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getNoteMetadata(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteMetadata, [noteId]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> saveNoteAnnotation(_i20.NoteAnnotation? annotation) =>
      (super.noSuchMethod(
            Invocation.method(#saveNoteAnnotation, [annotation]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i20.NoteAnnotation?> getNoteAnnotation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotation, [id]),
            returnValue: _i6.Future<_i20.NoteAnnotation?>.value(),
          )
          as _i6.Future<_i20.NoteAnnotation?>);

  @override
  _i6.Future<List<_i20.NoteAnnotation>> getNoteAnnotationsForNote(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotationsForNote, [noteId]),
            returnValue: _i6.Future<List<_i20.NoteAnnotation>>.value(
              <_i20.NoteAnnotation>[],
            ),
          )
          as _i6.Future<List<_i20.NoteAnnotation>>);

  @override
  _i6.Future<List<_i20.NoteAnnotation>> getNoteAnnotationsForAttachment(
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotationsForAttachment, [attachmentId]),
            returnValue: _i6.Future<List<_i20.NoteAnnotation>>.value(
              <_i20.NoteAnnotation>[],
            ),
          )
          as _i6.Future<List<_i20.NoteAnnotation>>);

  @override
  _i6.Future<void> deleteNoteAnnotation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteAnnotation, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateLastViewedPage(
    String? attachmentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastViewedPage, [
              attachmentId,
              pageNumber,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i21.Attachment?> getAttachmentById(String? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentById, [attachmentId]),
            returnValue: _i6.Future<_i21.Attachment?>.value(),
          )
          as _i6.Future<_i21.Attachment?>);

  @override
  _i6.Future<List<_i21.Attachment>> getAttachmentsForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsForNote, [noteId]),
            returnValue: _i6.Future<List<_i21.Attachment>>.value(
              <_i21.Attachment>[],
            ),
          )
          as _i6.Future<List<_i21.Attachment>>);

  @override
  _i6.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertSubNote(_i17.SubNote? subNote, String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#insertSubNote, [subNote, noteId]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertSubNote, [subNote, noteId]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i17.SubNote>> getSubNotes(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubNotes, [noteId]),
            returnValue: _i6.Future<List<_i17.SubNote>>.value(<_i17.SubNote>[]),
          )
          as _i6.Future<List<_i17.SubNote>>);

  @override
  _i6.Future<String> insertTag(_i22.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#insertTag, [tag]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertTag, [tag]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i22.Tag>> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue: _i6.Future<List<_i22.Tag>>.value(<_i22.Tag>[]),
          )
          as _i6.Future<List<_i22.Tag>>);

  @override
  _i6.Future<void> deleteTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tagName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setTagImage(String? tagId, String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#setTagImage, [tagId, imagePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeTagImage(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagImage, [tagId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, String>> getAllTagImages() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTagImages, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<String?> getTagImage(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagImage, [tagId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> replaceTag(String? oldTagName, String? newTagName) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTag, [oldTagName, newTagName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertRelationship(_i23.Relationship? relationship) =>
      (super.noSuchMethod(
            Invocation.method(#insertRelationship, [relationship]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertRelationship, [relationship]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i23.Relationship>> getRelationships(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getRelationships, [noteId]),
            returnValue: _i6.Future<List<_i23.Relationship>>.value(
              <_i23.Relationship>[],
            ),
          )
          as _i6.Future<List<_i23.Relationship>>);

  @override
  _i6.Future<List<_i23.Relationship>> getOutgoingRelationships(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOutgoingRelationships, [noteId]),
            returnValue: _i6.Future<List<_i23.Relationship>>.value(
              <_i23.Relationship>[],
            ),
          )
          as _i6.Future<List<_i23.Relationship>>);

  @override
  _i6.Future<List<_i23.Relationship>> getIncomingRelationships(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getIncomingRelationships, [noteId]),
            returnValue: _i6.Future<List<_i23.Relationship>>.value(
              <_i23.Relationship>[],
            ),
          )
          as _i6.Future<List<_i23.Relationship>>);

  @override
  _i6.Future<void> deleteRelationship(String? relationshipId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationship, [relationshipId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRelationshipBetween(
    String? fromNoteId,
    String? toNoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationshipBetween, [
              fromNoteId,
              toNoteId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteRelationshipsForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationshipsForNote, [noteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> relationshipExists(
    String? fromNoteId,
    String? toNoteId,
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#relationshipExists, [
              fromNoteId,
              toNoteId,
              type,
            ]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> verifyAttachmentPath(String? attachmentPath) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAttachmentPath, [attachmentPath]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String?> getNoteIdForAttachment(String? attachmentPath) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteIdForAttachment, [attachmentPath]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllAttachments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAttachments, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String> getDatabasePath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, []),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePath, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> checkpoint() =>
      (super.noSuchMethod(
            Invocation.method(#checkpoint, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> migrateBackupDatabase(
    _i4.Database? db,
    int? oldVersion,
    int? newVersion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#migrateBackupDatabase, [
              db,
              oldVersion,
              newVersion,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertFilter(_i24.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#insertFilter, [filter]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertFilter, [filter]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i24.Filter>> getAllFilters() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFilters, []),
            returnValue: _i6.Future<List<_i24.Filter>>.value(<_i24.Filter>[]),
          )
          as _i6.Future<List<_i24.Filter>>);

  @override
  _i6.Future<_i24.Filter?> getFilter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFilter, [id]),
            returnValue: _i6.Future<_i24.Filter?>.value(),
          )
          as _i6.Future<_i24.Filter?>);

  @override
  _i6.Future<void> updateFilter(_i24.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#updateFilter, [filter]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteFilter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFilter, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> executeRawQuery(String? sql) =>
      (super.noSuchMethod(
            Invocation.method(#executeRawQuery, [sql]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String> insertUserApp(_i25.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserApp, [app]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertUserApp, [app]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i25.UserApp>> getAllUserApps() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserApps, []),
            returnValue: _i6.Future<List<_i25.UserApp>>.value(<_i25.UserApp>[]),
          )
          as _i6.Future<List<_i25.UserApp>>);

  @override
  _i6.Future<_i25.UserApp?> getUserApp(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserApp, [id]),
            returnValue: _i6.Future<_i25.UserApp?>.value(),
          )
          as _i6.Future<_i25.UserApp?>);

  @override
  _i6.Future<void> updateUserApp(_i25.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserApp, [app]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserApp(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserApp, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserAppState(
    String? id,
    Map<String, dynamic>? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserAppState, [id, state]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserAppState(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppState, [id]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<String> insertAppRevision(_i26.AppRevision? revision) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppRevision, [revision]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertAppRevision, [revision]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i26.AppRevision>> getAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevisions, [appId]),
            returnValue: _i6.Future<List<_i26.AppRevision>>.value(
              <_i26.AppRevision>[],
            ),
          )
          as _i6.Future<List<_i26.AppRevision>>);

  @override
  _i6.Future<_i26.AppRevision?> getAppRevision(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevision, [id]),
            returnValue: _i6.Future<_i26.AppRevision?>.value(),
          )
          as _i6.Future<_i26.AppRevision?>);

  @override
  _i6.Future<void> deleteAppRevision(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevision, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevisions, [appId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> getNextRevisionNumber(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getNextRevisionNumber, [appId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i26.AppRevision?> getLatestAppRevision(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestAppRevision, [appId]),
            returnValue: _i6.Future<_i26.AppRevision?>.value(),
          )
          as _i6.Future<_i26.AppRevision?>);

  @override
  _i6.Future<int> insertUserAppLibrary({
    required String? appUuid,
    required int? revisionId,
    required String? name,
    String? usageInstructions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAppLibrary, [], {
              #appUuid: appUuid,
              #revisionId: revisionId,
              #name: name,
              #usageInstructions: usageInstructions,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getUserAppLibraries(
    String? appUuid,
    int? revisionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraries, [appUuid, revisionId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> deleteUserAppLibrary(int? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibrary, [libraryId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserAppLibrariesForRevision(int? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibrariesForRevision, [revisionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<int> insertUserAppLibraryDependency({
    String? originalUrl,
    required String? localPath,
    required List<int>? bytes,
    required int? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAppLibraryDependency, [], {
              #originalUrl: originalUrl,
              #localPath: localPath,
              #bytes: bytes,
              #libraryId: libraryId,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getUserAppLibraryDependencies(
    int? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraryDependencies, [libraryId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<Map<String, dynamic>?> getUserAppLibraryDependencyByPath(
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraryDependencyByPath, [localPath]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> deleteUserAppLibraryDependency(int? dependencyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibraryDependency, [dependencyId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>?> getDependencyByAppAndPath(
    String? appUuid,
    int? revisionId,
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDependencyByAppAndPath, [
              appUuid,
              revisionId,
              localPath,
            ]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<String> insertConversation(_i27.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversation, [conversation]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertConversation, [conversation]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i27.Conversation>> getAllConversations({
    Duration? maxAge,
    List<String>? conversationIds,
    List<String>? tagNames,
    bool? includeEmpty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {
              #maxAge: maxAge,
              #conversationIds: conversationIds,
              #tagNames: tagNames,
              #includeEmpty: includeEmpty,
            }),
            returnValue: _i6.Future<List<_i27.Conversation>>.value(
              <_i27.Conversation>[],
            ),
          )
          as _i6.Future<List<_i27.Conversation>>);

  @override
  _i6.Future<List<_i27.ConversationMessage>> getConversationPreviewMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationPreviewMessages, [
              conversationId,
            ]),
            returnValue: _i6.Future<List<_i27.ConversationMessage>>.value(
              <_i27.ConversationMessage>[],
            ),
          )
          as _i6.Future<List<_i27.ConversationMessage>>);

  @override
  _i6.Future<_i27.Conversation?> getConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [id]),
            returnValue: _i6.Future<_i27.Conversation?>.value(),
          )
          as _i6.Future<_i27.Conversation?>);

  @override
  _i6.Future<void> updateConversation(_i27.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertConversationMessage(
    _i27.ConversationMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessage, [message]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertConversationMessage, [message]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i27.ConversationMessage>> getConversationMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessages, [conversationId]),
            returnValue: _i6.Future<List<_i27.ConversationMessage>>.value(
              <_i27.ConversationMessage>[],
            ),
          )
          as _i6.Future<List<_i27.ConversationMessage>>);

  @override
  _i6.Future<_i27.ConversationMessage?> getConversationMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessage, [id]),
            returnValue: _i6.Future<_i27.ConversationMessage?>.value(),
          )
          as _i6.Future<_i27.ConversationMessage?>);

  @override
  _i6.Future<void> updateConversationMessage(
    _i27.ConversationMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationMessage, [message]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConversationMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationMessage, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessageWithSubtree(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessageWithSubtree, [messageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConversationExplicitly(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationExplicitly, [conversationId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteMessagesFromTreeNodes(List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessagesFromTreeNodes, [messageIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertConversationAttachment(
    _i28.ConversationAttachment? attachment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationAttachment, [attachment]),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertConversationAttachment, [attachment]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<_i28.ConversationAttachment>> getConversationAttachments(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationAttachments, [messageId]),
            returnValue: _i6.Future<List<_i28.ConversationAttachment>>.value(
              <_i28.ConversationAttachment>[],
            ),
          )
          as _i6.Future<List<_i28.ConversationAttachment>>);

  @override
  _i6.Future<void> deleteConversationAttachment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationAttachment, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String> insertConversationMessageMapping({
    required String? conversationId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessageMapping, [], {
              #conversationId: conversationId,
              #messageId: messageId,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertConversationMessageMapping, [], {
                  #conversationId: conversationId,
                  #messageId: messageId,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getConversationMessageMappings(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessageMappings, [
              conversationId,
            ]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<String>> getConversationMessageIds(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessageIds, [conversationId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<String> insertMessageParent({
    required String? messageId,
    required String? parentMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertMessageParent, [], {
              #messageId: messageId,
              #parentMessageId: parentMessageId,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertMessageParent, [], {
                  #messageId: messageId,
                  #parentMessageId: parentMessageId,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllMessageParents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMessageParents, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<String?> getMessageParent(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageParent, [messageId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<String>> getMessageChildren(String? parentMessageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageChildren, [parentMessageId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> deleteEmptyConversations({required Duration? olderThan}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmptyConversations, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getConversationsContainingMessage(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationsContainingMessage, [messageId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<String> insertConversationNoteMapping({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationNoteMapping, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#insertConversationNoteMapping, [], {
                  #conversationId: conversationId,
                  #noteId: noteId,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<List<String>> getConversationNoteIds(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationNoteIds, [conversationId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<List<String>> getNoteConversationIds(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationIds, [noteId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> deleteConversationNoteMapping({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationNoteMapping, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteConversationNoteMappings(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationNoteMappings, [
              conversationId,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteNoteConversationMappings(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteConversationMappings, [noteId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> conversationNoteMappingExists({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#conversationNoteMappingExists, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int> getNoteConversationCount(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationCount, [noteId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> getConversationNoteCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationNoteCount, [conversationId]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> addTagsToConversation(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTagsToConversation, [
              conversationId,
              tagNames,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setConversationTags(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationTags, [conversationId, tagNames]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeTagFromConversation(
    String? conversationId,
    String? tagName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromConversation, [
              conversationId,
              tagName,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i22.Tag>> getConversationTags(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTags, [conversationId]),
            returnValue: _i6.Future<List<_i22.Tag>>.value(<_i22.Tag>[]),
          )
          as _i6.Future<List<_i22.Tag>>);

  @override
  _i6.Future<List<String>> getConversationTagNames(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTagNames, [conversationId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> addAppToMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#addAppToMultiFunction, [appId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeAppFromMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppFromMultiFunction, [appId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setMultiFunctionDefaultApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setMultiFunctionDefaultApp, [appId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearMultiFunctionDefaultApp() =>
      (super.noSuchMethod(
            Invocation.method(#clearMultiFunctionDefaultApp, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getMultiFunctionApps() =>
      (super.noSuchMethod(
            Invocation.method(#getMultiFunctionApps, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<String?> getMultiFunctionDefaultAppId() =>
      (super.noSuchMethod(
            Invocation.method(#getMultiFunctionDefaultAppId, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<_i27.ConversationMessage>> getMessagesForConversations(
    List<String>? conversationIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesForConversations, [conversationIds]),
            returnValue: _i6.Future<List<_i27.ConversationMessage>>.value(
              <_i27.ConversationMessage>[],
            ),
          )
          as _i6.Future<List<_i27.ConversationMessage>>);

  @override
  _i6.Future<Map<String, List<String>>> getConversationIdsForMessages(
    List<String>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationIdsForMessages, [messageIds]),
            returnValue: _i6.Future<Map<String, List<String>>>.value(
              <String, List<String>>{},
            ),
          )
          as _i6.Future<Map<String, List<String>>>);

  @override
  _i6.Future<List<_i17.Note>> searchNotesFTS(
    String? query, {
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotesFTS, [query], {#tags: tags}),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> runRawQuery(
    String? query, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#runRawQuery, [query, arguments]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<_i17.Note>> searchNotes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue: _i6.Future<List<_i17.Note>>.value(<_i17.Note>[]),
          )
          as _i6.Future<List<_i17.Note>>);

  @override
  _i6.Future<String?> getTagExtractionPrompt(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagExtractionPrompt, [tagId]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> updateTagExtractionPrompt(String? tagId, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagExtractionPrompt, [tagId, prompt]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i17.Note?> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i6.Future<_i17.Note?>.value(),
          )
          as _i6.Future<_i17.Note?>);

  @override
  _i6.Future<_i29.WorkflowBindingRow?> getExactWorkflowBinding(
    String? tagName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExactWorkflowBinding, [tagName]),
            returnValue: _i6.Future<_i29.WorkflowBindingRow?>.value(),
          )
          as _i6.Future<_i29.WorkflowBindingRow?>);

  @override
  _i6.Future<List<_i29.WorkflowBindingRow>> getPrefixWorkflowBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getPrefixWorkflowBindings, []),
            returnValue: _i6.Future<List<_i29.WorkflowBindingRow>>.value(
              <_i29.WorkflowBindingRow>[],
            ),
          )
          as _i6.Future<List<_i29.WorkflowBindingRow>>);

  @override
  _i6.Future<_i29.WorkflowBindingRow?> getWorkflowBindingByPattern(
    String? pattern,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkflowBindingByPattern, [pattern]),
            returnValue: _i6.Future<_i29.WorkflowBindingRow?>.value(),
          )
          as _i6.Future<_i29.WorkflowBindingRow?>);

  @override
  _i6.Future<List<_i29.WorkflowBindingRow>> getAllWorkflowBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkflowBindings, []),
            returnValue: _i6.Future<List<_i29.WorkflowBindingRow>>.value(
              <_i29.WorkflowBindingRow>[],
            ),
          )
          as _i6.Future<List<_i29.WorkflowBindingRow>>);

  @override
  _i6.Future<void> insertWorkflowBinding(_i29.WorkflowBindingRow? binding) =>
      (super.noSuchMethod(
            Invocation.method(#insertWorkflowBinding, [binding]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWorkflowBinding(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkflowBinding, [pattern]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
