import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:note_synapse/models/agent_task.dart';
import 'package:note_synapse/models/context_node.dart';
import 'package:note_synapse/models/generation_context.dart';
import 'package:note_synapse/models/mcp_endpoint.dart';
import 'package:note_synapse/services/agent_service.dart';
import 'package:note_synapse/services/ai_service.dart';
import 'package:note_synapse/services/context_manager_service.dart';
import 'package:note_synapse/services/database_service.dart';
import 'package:note_synapse/services/model_selector.dart';
import 'package:note_synapse/services/prompts/prompt_template_service.dart';
import 'package:note_synapse/services/service_locator.dart';
import 'package:note_synapse/services/skill_service.dart';
import 'package:shared_preferences/shared_preferences.dart';

@GenerateMocks([
  ContextManagerService,
  ModelSelector,
  AIService,
  DatabaseService,
  PromptTemplateService,
])
import 'agent_service_test.mocks.dart';

// Mocks generated by Mockito

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  SharedPreferences.setMockInitialValues({});

  late MockContextManagerService mockContextManager;
  late MockModelSelector mockModelSelector;
  late MockAIService mockAIService;
  late MockDatabaseService mockDatabaseService;
  late MockPromptTemplateService mockPromptTemplateService;
  late AgentService agentService;

  setUp(() async {
    await resetForTesting();
    mockContextManager = MockContextManagerService();
    mockModelSelector = MockModelSelector();
    mockAIService = MockAIService();
    mockDatabaseService = MockDatabaseService();
    mockPromptTemplateService = MockPromptTemplateService();

    getIt.registerLazySingleton<ContextManagerService>(
      () => mockContextManager,
    );
    getIt.registerLazySingleton<ModelSelector>(() => mockModelSelector);
    getIt.registerLazySingleton<AIService>(() => mockAIService);
    getIt.registerLazySingleton<DatabaseService>(() => mockDatabaseService);
    getIt.registerLazySingleton<PromptTemplateService>(() => mockPromptTemplateService);
    getIt.registerLazySingleton<SkillService>(() => SkillService(mockDatabaseService));
    
    when(mockDatabaseService.getNotesByTag('agent-skill'))
        .thenAnswer((_) async => []);
    when(mockDatabaseService.searchNotesFTS(any, tags: anyNamed('tags')))
        .thenAnswer((_) async => []);
    when(mockPromptTemplateService.renderSync(any, any))
        .thenReturn('Mock Template Content');

    agentService = AgentService(
      mockContextManager,
      mockModelSelector,
      mockAIService,
      mockDatabaseService,
    );

    // Default mock behaviors
    when(mockContextManager.rootContext).thenReturn(null);
    when(
      mockContextManager.createRootContext(
        objective: anyNamed('objective'),
        allowedTools: anyNamed('allowedTools'),
        maxTokens: anyNamed('maxTokens'),
      ),
    ).thenAnswer(
      (invocation) async => ContextNode(
        id: 'root',
        objective: invocation.namedArguments[#objective],
      ),
    );

    when(
      mockContextManager.createChildContext(
        parent: anyNamed('parent'),
        objective: anyNamed('objective'),
        allowedTools: anyNamed('allowedTools'),
      ),
    ).thenAnswer(
      (invocation) => ContextNode(
        id: 'child',
        objective: invocation.namedArguments[#objective],
      ),
    );

    when(
      mockAIService.generateWithAttachments(
        any,
        any,
        generationContext: anyNamed('generationContext'),
      ),
    ).thenAnswer((_) async => 'Mock AI Response');

    when(mockContextManager.getContext(any)).thenReturn(null);

    // Default DatabaseService stubs
    when(
      mockDatabaseService.searchNotesFTS(any, tags: anyNamed('tags')),
    ).thenAnswer((_) async => []);
    when(mockDatabaseService.getNoteById(any)).thenAnswer((_) async => null);
    when(mockDatabaseService.getRelationships(any)).thenAnswer((_) async => []);

    // Default ContextManagerService stubs for non-nullable String returns
    when(
      mockContextManager.buildContextForNode(
        any,
        tocThreshold: anyNamed('tocThreshold'),
      ),
    ).thenReturn('Mock Context');
    when(
      mockContextManager.buildContextForResearchTask(
        any,
        dependencyResults: anyNamed('dependencyResults'),
        structuredDependencies: anyNamed('structuredDependencies'),
      ),
    ).thenReturn('Mock Research Context');
    when(
      mockContextManager.buildContextForSubtask(any),
    ).thenReturn('Mock Subtask Context');
    when(
      mockContextManager.buildSynthesisContext(
        any,
        structuredDependencies: anyNamed('structuredDependencies'),
      ),
    ).thenReturn('Mock Synthesis Context');

    // Default ModelSelector stubs
    when(mockModelSelector.currentModelConfig).thenReturn(null);
    when(mockModelSelector.dispose()).thenAnswer((_) => Future.value());
  });

  tearDown(() async {
    await resetForTesting();
  });

  group('AgentService Tool Executor', () {
    test('ToolExecutor typedef has correct signature', () {
      ToolExecutor executor =
          (
            String serviceName,
            String toolName,
            Map<String, dynamic> parameters,
            GenerationContext generationContext,
          ) async {
            return 'test result';
          };

      expect(executor, isNotNull);
    });

    test('generatePlan accepts executeTool parameter', () async {
      final executor =
          (
            String serviceName,
            String toolName,
            Map<String, dynamic> parameters,
            GenerationContext generationContext,
          ) async {
            // Capture for verification if needed, or just return success
            return 'executed';
          };

      final activeTools = <String, List<McpTool>>{
        'NS/test_tool_abc12345': [
          McpTool(
            name: 'test_tool',
            description: 'A test tool',
            inputSchema: {'type': 'object', 'properties': {}},
          ),
        ],
      };

      expect(
        () => agentService.generatePlan(
          'Test objective',
          activeTools: activeTools,
          executeTool: executor,
        ),
        returnsNormally,
      );
    });

    test('startObjective accepts executeTool parameter', () async {
      final executor =
          (
            String serviceName,
            String toolName,
            Map<String, dynamic> parameters,
            GenerationContext generationContext,
          ) async {
            return 'executed';
          };

      expect(
        () => agentService.startObjective(
          'Test objective',
          activeTools: const {},
          executeTool: executor,
        ),
        returnsNormally,
      );
    });

    test('clearState resets tool executor', () {
      agentService.clearState();

      expect(agentService.tasks, isEmpty);
      expect(agentService.isRunning, isFalse);
      expect(agentService.currentThought, isNull);
      expect(agentService.finalAnswer, isNull);
    });

    test('local AI tool service names use NS/ prefix pattern', () {
      final localToolServiceName = 'NS/my_tool_abc12345';
      final mcpServiceName = 'my-mcp-service';

      expect(localToolServiceName.startsWith('NS/'), isTrue);
      expect(mcpServiceName.startsWith('NS/'), isFalse);
    });
  });

  group('JSON extraction patterns', () {
    String? extractJsonFromResponse(String response) {
      // Logic copied from AgentService implementation for testing regex
      final jsonBlockMatch = RegExp(
        r'```json\s*(\{.*?\})\s*```',
        dotAll: true,
      ).firstMatch(response);

      if (jsonBlockMatch != null) {
        return jsonBlockMatch.group(1);
      }

      final jsonStartMatch = RegExp(
        r'\{\s*"(?:tool|answer|think|spawn_subtasks)"\s*:',
      ).firstMatch(response);

      if (jsonStartMatch != null) {
        final startIdx = jsonStartMatch.start;
        int braceCount = 0;
        int? endIdx;
        for (int i = startIdx; i < response.length; i++) {
          if (response[i] == '{') {
            braceCount++;
          } else if (response[i] == '}') {
            braceCount--;
            if (braceCount == 0) {
              endIdx = i + 1;
              break;
            }
          }
        }
        if (endIdx != null) {
          return response.substring(startIdx, endIdx);
        }
      }
      return null;
    }

    test('extracts valid JSON from code block', () {
      final response = '''
My thought: I have all the information needed.

```json
{ "answer": "The REST API endpoints are documented below." }
```
''';
      final json = extractJsonFromResponse(response);
      expect(json, isNotNull);
      expect(json, contains('"answer"'));
    });

    test('extracts JSON without code block', () {
      final response = '''
My thought: Analysis complete.

{ "answer": "Here is the summary." }
''';
      final json = extractJsonFromResponse(response);
      expect(json, isNotNull);
      expect(json, contains('"answer"'));
    });

    test('ignores template placeholders like {cid}', () {
      final response = '''
My thought: The endpoint uses GET https://api.example.com/{cid}/data
''';
      final json = extractJsonFromResponse(response);
      expect(json, isNull);
    });

    test('handles nested JSON objects', () {
      final response = '''
{ "tool": "search", "args": { "query": "test" } }
''';
      final json = extractJsonFromResponse(response);
      expect(json, isNotNull);
      expect(json, contains('"tool"'));
    });
  });

  group('Subtask spawning', () {
    test('kMaxSubtaskDepth constant is defined', () {
      expect(kMaxSubtaskDepth, equals(2));
    });

    test('AgentTask has spawnedSubtaskIds field', () {
      final task = AgentTask(id: 'test-id', description: 'Test task');
      expect(task.spawnedSubtaskIds, isEmpty);
      task.spawnedSubtaskIds.add('child-1');
      expect(task.spawnedSubtaskIds, contains('child-1'));
    });

    test('AgentTask has isSpawnedDynamically field', () {
      final plannedTask = AgentTask(id: 'planned-id', description: 'Planned');
      expect(plannedTask.isSpawnedDynamically, isFalse);

      final spawnedTask = AgentTask(
        id: 'spawned-id',
        description: 'Spawned',
        isSpawnedDynamically: true,
      );
      expect(spawnedTask.isSpawnedDynamically, isTrue);
    });
  });

  group('Task dependencies', () {
    test('AgentTask has name and dependsOn fields', () {
      final task = AgentTask(
        id: 'test-id',
        description: 'Test task',
        name: 'test_task',
        dependsOn: ['dep_a'],
      );
      expect(task.name, equals('test_task'));
      expect(task.dependsOn, equals(['dep_a']));
    });
  });
  group('Pause/Resume/Stop', () {
    test('pauseExecution sets isPaused when running', () {
      expect(agentService.isPaused, isFalse);
      agentService.pauseExecution(); // Not running, so it stays false
      expect(agentService.isPaused, isFalse);
    });

    test('stopExecution clears all state', () {
      agentService.stopExecution();
      expect(agentService.tasks, isEmpty);
      expect(agentService.isRunning, isFalse);
    });

    test('bindToConversation sets boundConversationId', () {
      agentService.bindToConversation('test-conv');
      expect(agentService.boundConversationId, equals('test-conv'));

      agentService.clearState();
      expect(agentService.boundConversationId, isNull);
    });

    test('canStartNewAgent logic', () {
      expect(agentService.canStartNewAgent('conv-1'), isTrue);

      agentService.bindToConversation('conv-1');
      expect(agentService.canStartNewAgent('conv-1'), isTrue);
    });
  });

  group('Agent Schema Validation', () {
    test('Agent detects orphaned arguments and reports schema error', () async {
      String? parseError;
      Map<String, dynamic>? decision;

      try {
        decision = {
          "owner": "google-gemini",
          "repo": "gemini-cli",
          "path": "packages",
        };
        if (!decision.containsKey('tool') &&
            !decision.containsKey('answer') &&
            !decision.containsKey('think') &&
            !decision.containsKey('spawn_subtasks')) {
          throw '''Invalid Agent Action: The parsed JSON object is missing a required action key. Found keys: ${decision.keys.toList()}.
You must use ONE of the following formats:

1. Call a Tool:
```json
{ "tool": "tool_name", "args": { ... } }
```

2. Answer (Final Result):
```json
{ "answer": "Your final answer here..." }
```
...''';
        }
      } catch (e) {
        parseError = e.toString();
      }
      expect(parseError, isNotNull);
      expect(parseError, contains("Invalid Agent Action"));
      expect(parseError, contains("Found keys: [owner, repo, path]"));
    });
  });

  group('AgentService - XML Tag Stripping in Final Deliverable Fallback', () {
    test(
      'REGRESSION: Final deliverable fallback should strip <answer> tags',
      () async {
        final task = AgentTask(
          id: 'final_story',
          name: 'write_story',
          description: 'Write a short detective story',
          isFinalDeliverable: true,
        );
        when(
          mockAIService.generateWithAttachments(
            any,
            any,
            generationContext: anyNamed('generationContext'),
          ),
        ).thenAnswer(
          (_) async => '''
<MyThought>Completing the story now.</MyThought>
<answer>
# The Detective's Last Case
Inspector Chen examined the crime scene carefully.
## The End
Justice was served.
</answer>
''',
        );
        await agentService.performTaskForTest(task, 'Story context');
        expect(task.status, equals(AgentTaskStatus.completed));
        expect(task.result, isNot(contains('<answer>')));
        expect(task.result, isNot(contains('</answer>')));
        expect(task.result, contains("Detective's Last Case"));
      },
    );

    test(
      'Final deliverable result already clean if XML parsing succeeds',
      () async {
        final task = AgentTask(
          id: 'clean_task',
          description: 'Clean task',
          isFinalDeliverable: true,
        );
        when(
          mockAIService.generateWithAttachments(
            any,
            any,
            generationContext: anyNamed('generationContext'),
          ),
        ).thenAnswer(
          (_) async => '''
<MyThought>Generating clean output.</MyThought>
<Action type="answer">
<Content>
# Clean Output
This is properly formatted content.
</Content>
</Action>
''',
        );
        await agentService.performTaskForTest(task, 'Context');
        expect(task.status, equals(AgentTaskStatus.completed));
        expect(task.result, isNot(contains('<Action')));
        expect(task.result, contains('Clean Output'));
      },
    );

    test('Fallback strips <MyThought> tags when XML parsing fails', () async {
      final task = AgentTask(
        id: 'thought_strip',
        description: 'Thought strip',
        isFinalDeliverable: true,
      );
      when(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).thenAnswer(
        (_) async => '''
<MyThought>This thought should be stripped.</MyThought>
# My Answer
This is the content that should remain.
''',
      );
      await agentService.performTaskForTest(task, 'Context');
      expect(task.status, equals(AgentTaskStatus.completed));
      expect(task.result, isNot(contains('<MyThought>')));
      expect(task.result, isNot(contains('This thought should be stripped')));
      expect(task.result, contains('My Answer'));
    });
  });

  group('AgentService - Tasks with Empty Tools Array', () {
    test('Task with empty tools array should invoke LLM', () async {
      bool llmWasCalled = false;
      final task = AgentTask(
        id: 'conceive_elements',
        description: 'Thinking task',
        toolNames: [],
        isFinalDeliverable: false,
      );
      when(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).thenAnswer((_) async {
        llmWasCalled = true;
        return '''
<Action type="answer">
<Content>Thought result</Content>
</Action>
''';
      });
      await agentService.performTaskForTest(task, 'Context');
      expect(llmWasCalled, isTrue);
      expect(task.status, equals(AgentTaskStatus.completed));
      expect(task.result, contains('Thought result'));
    });

    test('Creative writing task with no tools invokes LLM', () async {
      bool llmWasCalled = false;
      final task = AgentTask(
        id: 'create_outline',
        name: 'create_outline',
        description: 'Create novel outline',
        toolNames: [],
        isFinalDeliverable: false,
      );

      when(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).thenAnswer((_) async {
        llmWasCalled = true;
        return '''
<Action type="answer">
<Content># Novel Outline</Content>
</Action>
''';
      });

      await agentService.performTaskForTest(task, 'Context');
      expect(llmWasCalled, isTrue);
      expect(task.result, contains('Novel Outline'));
    });

    test(
      'Task with extractFindings=true and empty tools invokes LLM',
      () async {
        bool llmWasCalled = false;
        final task = AgentTask(
          id: 'extract_task',
          description: 'Extract findings',
          toolNames: [],
          extractFindings: true,
        );

        when(
          mockAIService.generateWithAttachments(
            any,
            any,
            generationContext: anyNamed('generationContext'),
          ),
        ).thenAnswer((_) async {
          llmWasCalled = true;
          return '''
<Action type="answer">
<Content>Findings extracted</Content>
</Action>
''';
        });

        await agentService.performTaskForTest(task, 'Context');
        expect(llmWasCalled, isTrue);
      },
    );

    test(
      'Task with isFinalDeliverable=true and empty tools invokes LLM',
      () async {
        bool llmWasCalled = false;
        final task = AgentTask(
          id: 'final_task',
          description: 'Final task',
          toolNames: [],
          isFinalDeliverable: true,
        );

        when(
          mockAIService.generateWithAttachments(
            any,
            any,
            generationContext: anyNamed('generationContext'),
          ),
        ).thenAnswer((_) async {
          llmWasCalled = true;
          return 'Final result';
        });

        await agentService.performTaskForTest(task, 'Context');
        expect(llmWasCalled, isTrue);
        expect(task.result, contains('Final result'));
      },
    );
  });

  group('AgentService - State Reset and Singleton Logic', () {
    test('canStartNewAgent returns correct logic', () {
      expect(agentService.canStartNewAgent('convo1'), isTrue);
      agentService.bindToConversation('convo1');
      expect(agentService.canStartNewAgent('convo1'), isTrue);
      expect(agentService.boundConversationId, 'convo1');
    });

    test('clearState resets all agent state correctly', () {
      agentService.bindToConversation('convo1');
      agentService.clearState();
      expect(agentService.boundConversationId, isNull);
      expect(agentService.tasks, isEmpty);
      expect(agentService.isRunning, isFalse);
    });

    test('abortCurrentTask clears state', () {
      agentService.bindToConversation('convo1');
      agentService.abortCurrentTask();
      expect(agentService.boundConversationId, isNull);
      expect(agentService.tasks, isEmpty);
    });
  });

  group('AgentService - Resume', () {
    test('resumeExecution should parse XML final answer', () async {
      reset(mockAIService);

      when(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).thenAnswer((invocation) async {
        final prompt = invocation.positionalArguments[0] as String;
        if (prompt.contains('You are an intelligent agent that plans')) {
          return '[{"name": "main_task", "description": "Just do it", "tools": [], "dependsOn": [], "isFinalDeliverable": true, "extractFindings": false}]';
        } else {
          return '<Action type="answer"><Content>parsed final result</Content></Action>';
        }
      });

      await agentService.startObjective("test");
      expect(agentService.finalAnswer, equals('parsed final result'));

      agentService.pauseExecution();
      await agentService.resumeExecution();
      expect(agentService.finalAnswer, equals('parsed final result'));

      verify(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).called(2);
    });
  });

  group('AgentService Logic Tests with XML Format', () {
    // Helper to run a single task step
    Future<void> runStep(AgentTask task, String mockLlmResponse) async {
      when(
        mockAIService.generateWithAttachments(
          any,
          any,
          generationContext: anyNamed('generationContext'),
        ),
      ).thenAnswer((_) async => mockLlmResponse);
      // Ensure search_notes is in allowed tools logic if needed
      task.toolNames = ['search_notes'];
      task.allowedTools = ['search_notes'];
      await agentService.performTaskForTest(task, "Global Context Placeholder");
    }

    test(
      'Case 1: Regular task, Missing Action element -> Error reported',
      () async {
        final task = AgentTask(
          id: '1',
          description: 'Regular task',
          isFinalDeliverable: false,
        );
        task.toolNames = ['search_notes'];
        when(
          mockAIService.generateWithAttachments(
            any,
            any,
            generationContext: anyNamed('generationContext'),
          ),
        ).thenAnswer((_) async => "I am thinking about this problem.");
        await agentService.performTaskForTest(task, "Context");
        expect(task.status, isNot(AgentTaskStatus.completed));
        expect(
          task.executionHistory.any((h) => h.contains('Missing <Action')),
          isTrue,
        );
      },
    );

    test(
      'Case 2: Regular task, Valid XML tool action -> performing action',
      () async {
        final task = AgentTask(
          id: '2',
          description: 'Regular task action',
          isFinalDeliverable: false,
        );
        const llmResponse = '''
<MyThought>I need to search for relevant notes.</MyThought>
<Action type="tool">
<ToolName>search_notes</ToolName>
<Content>{"query": "test"}</Content>
</Action>
''';
        await runStep(task, llmResponse);
        expect(
          task.executionHistory.any(
            (h) => h.contains('Action: Call System.search_notes'),
          ),
          isTrue,
        );
      },
    );

    test(
      'Case 3: Final Deliverable, Missing Action -> Complete as Answer (fallback)',
      () async {
        final task = AgentTask(
          id: '3',
          description: 'Final task',
          isFinalDeliverable: true,
        );
        final llmResponse = "Here is the final report.\n\n# Summary\nIt works.";
        await runStep(task, llmResponse);
        expect(task.status, equals(AgentTaskStatus.completed));
        expect(task.result, contains("Here is the final report"));
      },
    );

    test(
      'Case 4: Final Deliverable, Valid XML tool action -> Perform tool',
      () async {
        final task = AgentTask(
          id: '4',
          description: 'Final task needs info',
          isFinalDeliverable: true,
        );
        const llmResponse = '''
<MyThought>I need one more piece of information.</MyThought>
<Action type="tool">
<ToolName>search_notes</ToolName>
<Content>{"query": "final check"}</Content>
</Action>
''';
        await runStep(task, llmResponse);
        expect(
          task.executionHistory.any(
            (h) => h.contains('Action: Call System.search_notes'),
          ),
          isTrue,
        );
        expect(task.status, isNot(AgentTaskStatus.completed));
      },
    );

    test(
      'Case 5: Final Deliverable, Valid XML answer -> Complete with content',
      () async {
        final task = AgentTask(
          id: '5',
          description: 'Final task with answer',
          isFinalDeliverable: true,
        );
        const llmResponse = '''
<MyThought>I have all the information I need.</MyThought>
<Action type="answer">
<Content>
# Analysis Report
## Summary
The investigation reveals important findings.
## Findings
1. First finding
2. Second finding
</Content>
</Action>
''';
        await runStep(task, llmResponse);
        expect(task.status, equals(AgentTaskStatus.completed));
        expect(task.result, contains("# Analysis Report"));
        expect(task.result, contains("First finding"));
      },
    );

    test(
      'Case 6: Regular Task, Invalid action type -> Error in history',
      () async {
        final task = AgentTask(
          id: '6',
          description: 'Regular task with invalid type',
          isFinalDeliverable: false,
        );
        const llmResponse = '''
<MyThought>Doing something.</MyThought>
<Action type="invalid_action">
<Content>something</Content>
</Action>
''';
        await runStep(task, llmResponse);
        expect(task.status, isNot(AgentTaskStatus.completed));
        expect(
          task.executionHistory.any((h) => h.contains('Invalid action type')),
          isTrue,
        );
      },
    );

    test('Case 7: Tool action without ToolName -> Error reported', () async {
      final task = AgentTask(
        id: '7',
        description: 'Tool without name',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>I'll search.</MyThought>
<Action type="tool">
<Content>{"query": "test"}</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(task.status, isNot(AgentTaskStatus.completed));
      expect(
        task.executionHistory.any((h) => h.contains('<ToolName>')),
        isTrue,
      );
    });

    test(
      'Case 8: Tool action with invalid JSON args -> Error reported',
      () async {
        final task = AgentTask(
          id: '8',
          description: 'Tool with bad JSON',
          isFinalDeliverable: false,
        );
        const llmResponse = '''
<MyThought>Searching.</MyThought>
<Action type="tool">
<ToolName>search_notes</ToolName>
<Content>this is not valid json</Content>
</Action>
''';
        await runStep(task, llmResponse);
        expect(task.status, isNot(AgentTaskStatus.completed));
        expect(task.executionHistory.any((h) => h.contains('JSON')), isTrue);
      },
    );

    test('Case 9: Think action continues without tool call', () async {
      final task = AgentTask(
        id: '9',
        description: 'Think action',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>I need to analyze the data.</MyThought>
<Action type="think">
<Content>Looking at the patterns, I notice that the data shows...</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(task.status, isNot(AgentTaskStatus.completed));
      expect(task.executionHistory.any((h) => h.contains('Analysis:')), isTrue);
    });

    test('Case 10: spawn_subtasks action creates subtasks', () async {
      final task = AgentTask(
        id: '10',
        description: 'Complex task',
        isFinalDeliverable: false,
        depth: 0,
      );
      const llmResponse = '''
<MyThought>This is complex, I'll decompose it.</MyThought>
<Action type="spawn_subtasks">
<Content>[{"description": "Research topic A", "tools": ["search"]}, {"description": "Research topic B", "tools": ["search"]}]</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(task.spawnedSubtaskIds.length, equals(2));
    });

    test('Case 11: spawn_subtasks with invalid JSON -> Error', () async {
      final task = AgentTask(
        id: '11',
        description: 'Bad spawn',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>Decomposing.</MyThought>
<Action type="spawn_subtasks">
<Content>{"not": "an array"}</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(task.status, isNot(AgentTaskStatus.completed));
      expect(task.executionHistory.any((h) => h.contains('array')), isTrue);
    });

    test('Case 12: spawn_subtasks missing description -> Error', () async {
      final task = AgentTask(
        id: '12',
        description: 'Bad spawn fields',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>Decomposing.</MyThought>
<Action type="spawn_subtasks">
<Content>[{"tools": ["search"]}]</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(task.status, isNot(AgentTaskStatus.completed));
      expect(
        task.executionHistory.any((h) => h.contains('description')),
        isTrue,
      );
    });

    test('Case 13: Tool Content with code fences is handled', () async {
      final task = AgentTask(
        id: '13',
        description: 'Tool with fenced JSON',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>Searching with formatted args.</MyThought>
<Action type="tool">
<ToolName>search_notes</ToolName>
<Content>
```json
{"query": "test with fences"}
```
</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(
        task.executionHistory.any(
          (h) => h.contains('Action: Call System.search_notes'),
        ),
        isTrue,
      );
    });

    test('Case 14: Thought extraction from MyThought element', () async {
      final task = AgentTask(
        id: '14',
        description: 'Test thought extraction',
        isFinalDeliverable: false,
      );
      const llmResponse = '''
<MyThought>This is my detailed reasoning about the problem at hand.</MyThought>
<Action type="think">
<Content>Further analysis here.</Content>
</Action>
''';
      await runStep(task, llmResponse);
      expect(
        task.executionHistory.any(
          (h) => h.contains('Thought: This is my detailed reasoning'),
        ),
        isTrue,
      );
    });
  });

  group('read_task_result tool exemption', () {
    test('read_task_result is always available', () {
      final allNativeTools = agentService.nativeTools;
      final hasReadTaskResult = allNativeTools.any(
        (t) => t.name == 'read_task_result',
      );
      expect(hasReadTaskResult, isTrue);
    });
  });
}
