// Mocks generated by Mockito 5.4.6 from annotations
// in note_synapse/test/services/content_ingestion_approval_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i5;

import 'package:file_picker/file_picker.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:note_synapse/models/agent_task.dart' as _i20;
import 'package:note_synapse/models/app_revision.dart' as _i6;
import 'package:note_synapse/models/attachment.dart' as _i12;
import 'package:note_synapse/models/conversation.dart' as _i16;
import 'package:note_synapse/models/conversation_attachment.dart' as _i17;
import 'package:note_synapse/models/filter.dart' as _i15;
import 'package:note_synapse/models/generation_context.dart' as _i27;
import 'package:note_synapse/models/mcp_endpoint.dart' as _i21;
import 'package:note_synapse/models/model_config.dart' as _i23;
import 'package:note_synapse/models/note.dart' as _i9;
import 'package:note_synapse/models/note_annotation.dart' as _i11;
import 'package:note_synapse/models/relationship.dart' as _i14;
import 'package:note_synapse/models/tag.dart' as _i13;
import 'package:note_synapse/models/user_app.dart' as _i7;
import 'package:note_synapse/models/workflow_binding_row.dart' as _i18;
import 'package:note_synapse/providers/app_provider.dart' as _i26;
import 'package:note_synapse/services/agent_service.dart' as _i19;
import 'package:note_synapse/services/context_manager_service.dart' as _i4;
import 'package:note_synapse/services/database_service.dart' as _i3;
import 'package:note_synapse/services/tag_workflow_service.dart' as _i25;
import 'package:note_synapse/services/tools/note_tools.dart' as _i22;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRawWriteResult_1 extends _i1.SmartFake
    implements _i3.RawWriteResult {
  _FakeRawWriteResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContextManagerService_2 extends _i1.SmartFake
    implements _i4.ContextManagerService {
  _FakeContextManagerService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocale_3 extends _i1.SmartFake implements _i5.Locale {
  _FakeLocale_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppRevision_4 extends _i1.SmartFake implements _i6.AppRevision {
  _FakeAppRevision_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserApp_5 extends _i1.SmartFake implements _i7.UserApp {
  _FakeUserApp_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i8.Future<_i2.Database>.value(
              _FakeDatabase_0(this, Invocation.getter(#database)),
            ),
          )
          as _i8.Future<_i2.Database>);

  @override
  _i8.Future<void> insertConversationMessageMappingsBatch(
    String? conversationId,
    List<String>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessageMappingsBatch, [
              conversationId,
              messageIds,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> validateConversationNotes(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#validateConversationNotes, [conversationId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> insertNote(_i9.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#insertNote, [note]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertNote, [note]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i9.Note>> getAllNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllNotes, []),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<void> cleanupInvalidNoteReferences() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupInvalidNoteReferences, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i9.Note>> getNotesByArchiveStatus({bool? isArchived}) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByArchiveStatus, [], {
              #isArchived: isArchived,
            }),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<List<_i9.Note>> getPinnedNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getPinnedNotes, []),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<List<_i9.Note>> getArchivedNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getArchivedNotes, []),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<_i9.Note?> getNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNote, [id]),
            returnValue: _i8.Future<_i9.Note?>.value(),
          )
          as _i8.Future<_i9.Note?>);

  @override
  _i8.Future<List<_i9.Note>> getNotesByIds(List<String>? noteIds) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByIds, [noteIds]),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<List<_i9.Note>> getNotesByTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByTag, [tagName]),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<void> updateNote(_i9.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateAttachmentAIContext(
    String? noteId,
    String? filePath,
    bool? include,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttachmentAIContext, [
              noteId,
              filePath,
              include,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateAttachmentMetadata(
    String? attachmentId,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateAttachmentMetadata, [
              attachmentId,
              metadata,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateNoteMetadata(
    String? noteId,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteMetadata, [noteId, metadata]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getNoteMetadata(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteMetadata, [noteId]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> saveNoteAnnotation(_i11.NoteAnnotation? annotation) =>
      (super.noSuchMethod(
            Invocation.method(#saveNoteAnnotation, [annotation]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i11.NoteAnnotation?> getNoteAnnotation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotation, [id]),
            returnValue: _i8.Future<_i11.NoteAnnotation?>.value(),
          )
          as _i8.Future<_i11.NoteAnnotation?>);

  @override
  _i8.Future<List<_i11.NoteAnnotation>> getNoteAnnotationsForNote(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotationsForNote, [noteId]),
            returnValue: _i8.Future<List<_i11.NoteAnnotation>>.value(
              <_i11.NoteAnnotation>[],
            ),
          )
          as _i8.Future<List<_i11.NoteAnnotation>>);

  @override
  _i8.Future<List<_i11.NoteAnnotation>> getNoteAnnotationsForAttachment(
    String? attachmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteAnnotationsForAttachment, [attachmentId]),
            returnValue: _i8.Future<List<_i11.NoteAnnotation>>.value(
              <_i11.NoteAnnotation>[],
            ),
          )
          as _i8.Future<List<_i11.NoteAnnotation>>);

  @override
  _i8.Future<void> deleteNoteAnnotation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteAnnotation, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateLastViewedPage(
    String? attachmentId,
    int? pageNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastViewedPage, [
              attachmentId,
              pageNumber,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i12.Attachment?> getAttachmentById(String? attachmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentById, [attachmentId]),
            returnValue: _i8.Future<_i12.Attachment?>.value(),
          )
          as _i8.Future<_i12.Attachment?>);

  @override
  _i8.Future<List<_i12.Attachment>> getAttachmentsForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getAttachmentsForNote, [noteId]),
            returnValue: _i8.Future<List<_i12.Attachment>>.value(
              <_i12.Attachment>[],
            ),
          )
          as _i8.Future<List<_i12.Attachment>>);

  @override
  _i8.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertSubNote(_i9.SubNote? subNote, String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#insertSubNote, [subNote, noteId]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertSubNote, [subNote, noteId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i9.SubNote>> getSubNotes(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubNotes, [noteId]),
            returnValue: _i8.Future<List<_i9.SubNote>>.value(<_i9.SubNote>[]),
          )
          as _i8.Future<List<_i9.SubNote>>);

  @override
  _i8.Future<String> insertTag(_i13.Tag? tag) =>
      (super.noSuchMethod(
            Invocation.method(#insertTag, [tag]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertTag, [tag]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i13.Tag>> getAllTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTags, []),
            returnValue: _i8.Future<List<_i13.Tag>>.value(<_i13.Tag>[]),
          )
          as _i8.Future<List<_i13.Tag>>);

  @override
  _i8.Future<void> deleteTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setTagImage(String? tagId, String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#setTagImage, [tagId, imagePath]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTagImage(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagImage, [tagId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, String>> getAllTagImages() =>
      (super.noSuchMethod(
            Invocation.method(#getAllTagImages, []),
            returnValue: _i8.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<String?> getTagImage(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagImage, [tagId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> replaceTag(String? oldTagName, String? newTagName) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTag, [oldTagName, newTagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertRelationship(_i14.Relationship? relationship) =>
      (super.noSuchMethod(
            Invocation.method(#insertRelationship, [relationship]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertRelationship, [relationship]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i14.Relationship>> getRelationships(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getRelationships, [noteId]),
            returnValue: _i8.Future<List<_i14.Relationship>>.value(
              <_i14.Relationship>[],
            ),
          )
          as _i8.Future<List<_i14.Relationship>>);

  @override
  _i8.Future<List<_i14.Relationship>> getOutgoingRelationships(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOutgoingRelationships, [noteId]),
            returnValue: _i8.Future<List<_i14.Relationship>>.value(
              <_i14.Relationship>[],
            ),
          )
          as _i8.Future<List<_i14.Relationship>>);

  @override
  _i8.Future<List<_i14.Relationship>> getIncomingRelationships(
    String? noteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getIncomingRelationships, [noteId]),
            returnValue: _i8.Future<List<_i14.Relationship>>.value(
              <_i14.Relationship>[],
            ),
          )
          as _i8.Future<List<_i14.Relationship>>);

  @override
  _i8.Future<void> deleteRelationship(String? relationshipId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationship, [relationshipId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRelationshipBetween(
    String? fromNoteId,
    String? toNoteId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationshipBetween, [
              fromNoteId,
              toNoteId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRelationshipsForNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationshipsForNote, [noteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> relationshipExists(
    String? fromNoteId,
    String? toNoteId,
    String? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#relationshipExists, [
              fromNoteId,
              toNoteId,
              type,
            ]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> verifyAttachmentPath(String? attachmentPath) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAttachmentPath, [attachmentPath]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<String?> getNoteIdForAttachment(String? attachmentPath) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteIdForAttachment, [attachmentPath]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAllAttachments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAttachments, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<String> getDatabasePath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, []),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePath, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> checkpoint() =>
      (super.noSuchMethod(
            Invocation.method(#checkpoint, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> migrateBackupDatabase(
    _i2.Database? db,
    int? oldVersion,
    int? newVersion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#migrateBackupDatabase, [
              db,
              oldVersion,
              newVersion,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertFilter(_i15.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#insertFilter, [filter]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertFilter, [filter]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i15.Filter>> getAllFilters() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFilters, []),
            returnValue: _i8.Future<List<_i15.Filter>>.value(<_i15.Filter>[]),
          )
          as _i8.Future<List<_i15.Filter>>);

  @override
  _i8.Future<_i15.Filter?> getFilter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFilter, [id]),
            returnValue: _i8.Future<_i15.Filter?>.value(),
          )
          as _i8.Future<_i15.Filter?>);

  @override
  _i8.Future<void> updateFilter(_i15.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#updateFilter, [filter]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteFilter(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFilter, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<Map<String, dynamic>>> executeRawQuery(String? sql) =>
      (super.noSuchMethod(
            Invocation.method(#executeRawQuery, [sql]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<String> insertUserApp(_i7.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserApp, [app]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertUserApp, [app]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i7.UserApp>> getAllUserApps() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUserApps, []),
            returnValue: _i8.Future<List<_i7.UserApp>>.value(<_i7.UserApp>[]),
          )
          as _i8.Future<List<_i7.UserApp>>);

  @override
  _i8.Future<_i7.UserApp?> getUserApp(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserApp, [id]),
            returnValue: _i8.Future<_i7.UserApp?>.value(),
          )
          as _i8.Future<_i7.UserApp?>);

  @override
  _i8.Future<_i7.UserApp?> getUserAppByUuid(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppByUuid, [uuid]),
            returnValue: _i8.Future<_i7.UserApp?>.value(),
          )
          as _i8.Future<_i7.UserApp?>);

  @override
  _i8.Future<void> updateUserApp(_i7.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserApp, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteUserApp(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserApp, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserAppState(
    String? id,
    Map<String, dynamic>? state,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserAppState, [id, state]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getUserAppState(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppState, [id]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<String> insertAppRevision(_i6.AppRevision? revision) =>
      (super.noSuchMethod(
            Invocation.method(#insertAppRevision, [revision]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertAppRevision, [revision]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i6.AppRevision>> getAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevisions, [appId]),
            returnValue: _i8.Future<List<_i6.AppRevision>>.value(
              <_i6.AppRevision>[],
            ),
          )
          as _i8.Future<List<_i6.AppRevision>>);

  @override
  _i8.Future<_i6.AppRevision?> getAppRevision(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevision, [id]),
            returnValue: _i8.Future<_i6.AppRevision?>.value(),
          )
          as _i8.Future<_i6.AppRevision?>);

  @override
  _i8.Future<void> deleteAppRevision(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevision, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevisions, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getNextRevisionNumber(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getNextRevisionNumber, [appId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<_i6.AppRevision?> getLatestAppRevision(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestAppRevision, [appId]),
            returnValue: _i8.Future<_i6.AppRevision?>.value(),
          )
          as _i8.Future<_i6.AppRevision?>);

  @override
  _i8.Future<int> insertUserAppLibrary({
    required String? appUuid,
    required int? revisionId,
    required String? name,
    String? usageInstructions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAppLibrary, [], {
              #appUuid: appUuid,
              #revisionId: revisionId,
              #name: name,
              #usageInstructions: usageInstructions,
            }),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getUserAppLibraries(
    String? appUuid,
    int? revisionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraries, [appUuid, revisionId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<void> deleteUserAppLibrary(int? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibrary, [libraryId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteUserAppLibrariesForRevision(int? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibrariesForRevision, [revisionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> insertUserAppLibraryDependency({
    String? originalUrl,
    required String? localPath,
    required List<int>? bytes,
    required int? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertUserAppLibraryDependency, [], {
              #originalUrl: originalUrl,
              #localPath: localPath,
              #bytes: bytes,
              #libraryId: libraryId,
            }),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getUserAppLibraryDependencies(
    int? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraryDependencies, [libraryId]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>?> getUserAppLibraryDependencyByPath(
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAppLibraryDependencyByPath, [localPath]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> deleteUserAppLibraryDependency(int? dependencyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserAppLibraryDependency, [dependencyId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> getDependencyByAppAndPath(
    String? appUuid,
    int? revisionId,
    String? localPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDependencyByAppAndPath, [
              appUuid,
              revisionId,
              localPath,
            ]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<String> insertConversation(_i16.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversation, [conversation]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertConversation, [conversation]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i16.Conversation>> getAllConversations({
    Duration? maxAge,
    List<String>? conversationIds,
    List<String>? tagNames,
    bool? includeEmpty = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {
              #maxAge: maxAge,
              #conversationIds: conversationIds,
              #tagNames: tagNames,
              #includeEmpty: includeEmpty,
            }),
            returnValue: _i8.Future<List<_i16.Conversation>>.value(
              <_i16.Conversation>[],
            ),
          )
          as _i8.Future<List<_i16.Conversation>>);

  @override
  _i8.Future<List<_i16.ConversationMessage>> getConversationPreviewMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationPreviewMessages, [
              conversationId,
            ]),
            returnValue: _i8.Future<List<_i16.ConversationMessage>>.value(
              <_i16.ConversationMessage>[],
            ),
          )
          as _i8.Future<List<_i16.ConversationMessage>>);

  @override
  _i8.Future<_i16.Conversation?> getConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [id]),
            returnValue: _i8.Future<_i16.Conversation?>.value(),
          )
          as _i8.Future<_i16.Conversation?>);

  @override
  _i8.Future<void> updateConversation(_i16.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertConversationMessage(
    _i16.ConversationMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessage, [message]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertConversationMessage, [message]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i16.ConversationMessage>> getConversationMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessages, [conversationId]),
            returnValue: _i8.Future<List<_i16.ConversationMessage>>.value(
              <_i16.ConversationMessage>[],
            ),
          )
          as _i8.Future<List<_i16.ConversationMessage>>);

  @override
  _i8.Future<_i16.ConversationMessage?> getConversationMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessage, [id]),
            returnValue: _i8.Future<_i16.ConversationMessage?>.value(),
          )
          as _i8.Future<_i16.ConversationMessage?>);

  @override
  _i8.Future<void> updateConversationMessage(
    _i16.ConversationMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationMessage, [message]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteConversationMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationMessage, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteMessageWithSubtree(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessageWithSubtree, [messageId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteConversationExplicitly(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationExplicitly, [conversationId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteMessagesFromTreeNodes(List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessagesFromTreeNodes, [messageIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertConversationAttachment(
    _i17.ConversationAttachment? attachment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationAttachment, [attachment]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertConversationAttachment, [attachment]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i17.ConversationAttachment>> getConversationAttachments(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationAttachments, [messageId]),
            returnValue: _i8.Future<List<_i17.ConversationAttachment>>.value(
              <_i17.ConversationAttachment>[],
            ),
          )
          as _i8.Future<List<_i17.ConversationAttachment>>);

  @override
  _i8.Future<void> deleteConversationAttachment(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationAttachment, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String> insertConversationMessageMapping({
    required String? conversationId,
    required String? messageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationMessageMapping, [], {
              #conversationId: conversationId,
              #messageId: messageId,
            }),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertConversationMessageMapping, [], {
                  #conversationId: conversationId,
                  #messageId: messageId,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getConversationMessageMappings(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessageMappings, [
              conversationId,
            ]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<String>> getConversationMessageIds(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessageIds, [conversationId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> insertMessageParent({
    required String? messageId,
    required String? parentMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertMessageParent, [], {
              #messageId: messageId,
              #parentMessageId: parentMessageId,
            }),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertMessageParent, [], {
                  #messageId: messageId,
                  #parentMessageId: parentMessageId,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAllMessageParents() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMessageParents, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<String?> getMessageParent(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageParent, [messageId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<List<String>> getMessageChildren(String? parentMessageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageChildren, [parentMessageId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> deleteEmptyConversations({required Duration? olderThan}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmptyConversations, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getConversationsContainingMessage(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationsContainingMessage, [messageId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String> insertConversationNoteMapping({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversationNoteMapping, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertConversationNoteMapping, [], {
                  #conversationId: conversationId,
                  #noteId: noteId,
                }),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<String>> getConversationNoteIds(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationNoteIds, [conversationId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<List<String>> getNoteConversationIds(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationIds, [noteId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> deleteConversationNoteMapping({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationNoteMapping, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteConversationNoteMappings(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversationNoteMappings, [
              conversationId,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteNoteConversationMappings(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNoteConversationMappings, [noteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> conversationNoteMappingExists({
    required String? conversationId,
    required String? noteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#conversationNoteMappingExists, [], {
              #conversationId: conversationId,
              #noteId: noteId,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<int> getNoteConversationCount(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationCount, [noteId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> getConversationNoteCount(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationNoteCount, [conversationId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> addTagsToConversation(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTagsToConversation, [
              conversationId,
              tagNames,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setConversationTags(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationTags, [conversationId, tagNames]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTagFromConversation(
    String? conversationId,
    String? tagName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromConversation, [
              conversationId,
              tagName,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i13.Tag>> getConversationTags(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTags, [conversationId]),
            returnValue: _i8.Future<List<_i13.Tag>>.value(<_i13.Tag>[]),
          )
          as _i8.Future<List<_i13.Tag>>);

  @override
  _i8.Future<List<String>> getConversationTagNames(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTagNames, [conversationId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> addAppToMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#addAppToMultiFunction, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeAppFromMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppFromMultiFunction, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setMultiFunctionDefaultApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setMultiFunctionDefaultApp, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearMultiFunctionDefaultApp() =>
      (super.noSuchMethod(
            Invocation.method(#clearMultiFunctionDefaultApp, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> getMultiFunctionApps() =>
      (super.noSuchMethod(
            Invocation.method(#getMultiFunctionApps, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<String?> getMultiFunctionDefaultAppId() =>
      (super.noSuchMethod(
            Invocation.method(#getMultiFunctionDefaultAppId, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<List<_i16.ConversationMessage>> getMessagesForConversations(
    List<String>? conversationIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesForConversations, [conversationIds]),
            returnValue: _i8.Future<List<_i16.ConversationMessage>>.value(
              <_i16.ConversationMessage>[],
            ),
          )
          as _i8.Future<List<_i16.ConversationMessage>>);

  @override
  _i8.Future<Map<String, List<String>>> getConversationIdsForMessages(
    List<String>? messageIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationIdsForMessages, [messageIds]),
            returnValue: _i8.Future<Map<String, List<String>>>.value(
              <String, List<String>>{},
            ),
          )
          as _i8.Future<Map<String, List<String>>>);

  @override
  _i8.Future<List<_i9.Note>> searchNotesFTS(
    String? query, {
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotesFTS, [query], {#tags: tags}),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> runRawQuery(
    String? query, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#runRawQuery, [query, arguments]),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  void markSchemaChangedForCapture() => super.noSuchMethod(
    Invocation.method(#markSchemaChangedForCapture, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i3.RawWriteResult> runRawWriteWithChangeCapture(String? sql) =>
      (super.noSuchMethod(
            Invocation.method(#runRawWriteWithChangeCapture, [sql]),
            returnValue: _i8.Future<_i3.RawWriteResult>.value(
              _FakeRawWriteResult_1(
                this,
                Invocation.method(#runRawWriteWithChangeCapture, [sql]),
              ),
            ),
          )
          as _i8.Future<_i3.RawWriteResult>);

  @override
  _i8.Future<List<_i9.Note>> searchNotes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchNotes, [query]),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<String?> getTagExtractionPrompt(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagExtractionPrompt, [tagId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> updateTagExtractionPrompt(String? tagId, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagExtractionPrompt, [tagId, prompt]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i9.Note?> getNoteById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteById, [id]),
            returnValue: _i8.Future<_i9.Note?>.value(),
          )
          as _i8.Future<_i9.Note?>);

  @override
  _i8.Future<_i18.WorkflowBindingRow?> getExactWorkflowBinding(
    String? tagName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExactWorkflowBinding, [tagName]),
            returnValue: _i8.Future<_i18.WorkflowBindingRow?>.value(),
          )
          as _i8.Future<_i18.WorkflowBindingRow?>);

  @override
  _i8.Future<List<_i18.WorkflowBindingRow>> getPrefixWorkflowBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getPrefixWorkflowBindings, []),
            returnValue: _i8.Future<List<_i18.WorkflowBindingRow>>.value(
              <_i18.WorkflowBindingRow>[],
            ),
          )
          as _i8.Future<List<_i18.WorkflowBindingRow>>);

  @override
  _i8.Future<_i18.WorkflowBindingRow?> getWorkflowBindingByPattern(
    String? pattern,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkflowBindingByPattern, [pattern]),
            returnValue: _i8.Future<_i18.WorkflowBindingRow?>.value(),
          )
          as _i8.Future<_i18.WorkflowBindingRow?>);

  @override
  _i8.Future<List<_i18.WorkflowBindingRow>> getAllWorkflowBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getAllWorkflowBindings, []),
            returnValue: _i8.Future<List<_i18.WorkflowBindingRow>>.value(
              <_i18.WorkflowBindingRow>[],
            ),
          )
          as _i8.Future<List<_i18.WorkflowBindingRow>>);

  @override
  _i8.Future<void> insertWorkflowBinding(_i18.WorkflowBindingRow? binding) =>
      (super.noSuchMethod(
            Invocation.method(#insertWorkflowBinding, [binding]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteWorkflowBinding(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWorkflowBinding, [pattern]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AgentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentService extends _i1.Mock implements _i19.AgentService {
  MockAgentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pendingWorkflowCount =>
      (super.noSuchMethod(
            Invocation.getter(#pendingWorkflowCount),
            returnValue: 0,
          )
          as int);

  @override
  List<_i19.PendingWorkflowInfo> get pendingWorkflows =>
      (super.noSuchMethod(
            Invocation.getter(#pendingWorkflows),
            returnValue: <_i19.PendingWorkflowInfo>[],
          )
          as List<_i19.PendingWorkflowInfo>);

  @override
  bool get isPaused =>
      (super.noSuchMethod(Invocation.getter(#isPaused), returnValue: false)
          as bool);

  @override
  _i4.ContextManagerService get contextManager =>
      (super.noSuchMethod(
            Invocation.getter(#contextManager),
            returnValue: _FakeContextManagerService_2(
              this,
              Invocation.getter(#contextManager),
            ),
          )
          as _i4.ContextManagerService);

  @override
  List<String> get globalContextNoteIds =>
      (super.noSuchMethod(
            Invocation.getter(#globalContextNoteIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i20.AgentTask> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: <_i20.AgentTask>[],
          )
          as List<_i20.AgentTask>);

  @override
  Map<String, List<_i21.McpTool>> get externalTools =>
      (super.noSuchMethod(
            Invocation.getter(#externalTools),
            returnValue: <String, List<_i21.McpTool>>{},
          )
          as Map<String, List<_i21.McpTool>>);

  @override
  List<_i22.NativeTool> get enabledNativeTools =>
      (super.noSuchMethod(
            Invocation.getter(#enabledNativeTools),
            returnValue: <_i22.NativeTool>[],
          )
          as List<_i22.NativeTool>);

  @override
  bool get isRunning =>
      (super.noSuchMethod(Invocation.getter(#isRunning), returnValue: false)
          as bool);

  @override
  List<_i22.NativeTool> get nativeTools =>
      (super.noSuchMethod(
            Invocation.getter(#nativeTools),
            returnValue: <_i22.NativeTool>[],
          )
          as List<_i22.NativeTool>);

  @override
  set onProgressUpdate(void Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onProgressUpdate, value),
    returnValueForMissingStub: null,
  );

  @override
  set modelOverride(_i23.ModelConfig? value) => super.noSuchMethod(
    Invocation.setter(#modelOverride, value),
    returnValueForMissingStub: null,
  );

  @override
  set toolExecutor(_i19.ToolExecutor? executor) => super.noSuchMethod(
    Invocation.setter(#toolExecutor, executor),
    returnValueForMissingStub: null,
  );

  @override
  set externalToolsForTest(Map<String, List<_i21.McpTool>>? tools) =>
      super.noSuchMethod(
        Invocation.setter(#externalToolsForTest, tools),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void cancelPendingWorkflow(int? index) => super.noSuchMethod(
    Invocation.method(#cancelPendingWorkflow, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i19.WorkflowStatusSnapshot? workflowStatusForNote(String? noteId) =>
      (super.noSuchMethod(Invocation.method(#workflowStatusForNote, [noteId]))
          as _i19.WorkflowStatusSnapshot?);

  @override
  void addGlobalContextNote(String? noteId) => super.noSuchMethod(
    Invocation.method(#addGlobalContextNote, [noteId]),
    returnValueForMissingStub: null,
  );

  @override
  void removeGlobalContextNote(String? noteId) => super.noSuchMethod(
    Invocation.method(#removeGlobalContextNote, [noteId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearGlobalContextNotes() => super.noSuchMethod(
    Invocation.method(#clearGlobalContextNotes, []),
    returnValueForMissingStub: null,
  );

  @override
  void setGlobalContextNotes(List<String>? noteIds) => super.noSuchMethod(
    Invocation.method(#setGlobalContextNotes, [noteIds]),
    returnValueForMissingStub: null,
  );

  @override
  void clearState() => super.noSuchMethod(
    Invocation.method(#clearState, []),
    returnValueForMissingStub: null,
  );

  @override
  void pauseExecution() => super.noSuchMethod(
    Invocation.method(#pauseExecution, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> resumeExecution() =>
      (super.noSuchMethod(
            Invocation.method(#resumeExecution, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void stopExecution() => super.noSuchMethod(
    Invocation.method(#stopExecution, []),
    returnValueForMissingStub: null,
  );

  @override
  void bindToConversation(String? conversationId) => super.noSuchMethod(
    Invocation.method(#bindToConversation, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  bool canStartNewAgent(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#canStartNewAgent, [conversationId]),
            returnValue: false,
          )
          as bool);

  @override
  void abortCurrentTask() => super.noSuchMethod(
    Invocation.method(#abortCurrentTask, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> performTaskForTest(
    _i20.AgentTask? task,
    String? globalContext,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#performTaskForTest, [task, globalContext]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, String> getToolToServiceMap() =>
      (super.noSuchMethod(
            Invocation.method(#getToolToServiceMap, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  List<String> getAllToolNames() =>
      (super.noSuchMethod(
            Invocation.method(#getAllToolNames, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<List<_i20.AgentTask>> generatePlan(
    String? objective, {
    Map<String, List<_i21.McpTool>>? activeTools = const {},
    _i19.ToolExecutor? executeTool,
    String? context,
    List<_i24.PlatformFile>? contextAttachments = const [],
    bool? skillsEnabled = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generatePlan,
              [objective],
              {
                #activeTools: activeTools,
                #executeTool: executeTool,
                #context: context,
                #contextAttachments: contextAttachments,
                #skillsEnabled: skillsEnabled,
              },
            ),
            returnValue: _i8.Future<List<_i20.AgentTask>>.value(
              <_i20.AgentTask>[],
            ),
          )
          as _i8.Future<List<_i20.AgentTask>>);

  @override
  _i8.Future<List<_i20.AgentTask>> revisePlan(String? feedback) =>
      (super.noSuchMethod(
            Invocation.method(#revisePlan, [feedback]),
            returnValue: _i8.Future<List<_i20.AgentTask>>.value(
              <_i20.AgentTask>[],
            ),
          )
          as _i8.Future<List<_i20.AgentTask>>);

  @override
  _i8.Future<void> executePlan() =>
      (super.noSuchMethod(
            Invocation.method(#executePlan, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> startObjective(
    String? objective, {
    Map<String, List<_i21.McpTool>>? activeTools = const {},
    _i19.ToolExecutor? executeTool,
    String? context,
    List<_i24.PlatformFile>? contextAttachments = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startObjective,
              [objective],
              {
                #activeTools: activeTools,
                #executeTool: executeTool,
                #context: context,
                #contextAttachments: contextAttachments,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void cancel() => super.noSuchMethod(
    Invocation.method(#cancel, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> runWorkflowTask({
    required _i25.ResolvedBinding? binding,
    required _i9.Note? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#runWorkflowTask, [], {
              #binding: binding,
              #note: note,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resumeTask(String? taskId, {bool? increaseLimit = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #resumeTask,
              [taskId],
              {#increaseLimit: increaseLimit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void concludeTask(String? taskId) => super.noSuchMethod(
    Invocation.method(#concludeTask, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void abortTask(String? taskId) => super.noSuchMethod(
    Invocation.method(#abortTask, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateToolExecutor(_i19.ToolExecutor? executor) => super.noSuchMethod(
    Invocation.method(#updateToolExecutor, [executor]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TagWorkflowService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTagWorkflowService extends _i1.Mock
    implements _i25.TagWorkflowService {
  MockTagWorkflowService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i25.ResolvedBinding>> resolveBindings(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#resolveBindings, [tags]),
            returnValue: _i8.Future<List<_i25.ResolvedBinding>>.value(
              <_i25.ResolvedBinding>[],
            ),
          )
          as _i8.Future<List<_i25.ResolvedBinding>>);

  @override
  _i8.Future<bool> hasImmutableBinding(List<String>? tags) =>
      (super.noSuchMethod(
            Invocation.method(#hasImmutableBinding, [tags]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i18.WorkflowBindingRow?> getBindingByPattern(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#getBindingByPattern, [pattern]),
            returnValue: _i8.Future<_i18.WorkflowBindingRow?>.value(),
          )
          as _i8.Future<_i18.WorkflowBindingRow?>);

  @override
  _i8.Future<List<_i18.WorkflowBindingRow>> getAllBindings() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBindings, []),
            returnValue: _i8.Future<List<_i18.WorkflowBindingRow>>.value(
              <_i18.WorkflowBindingRow>[],
            ),
          )
          as _i8.Future<List<_i18.WorkflowBindingRow>>);

  @override
  _i8.Future<void> registerBinding({
    required String? pattern,
    required bool? isPrefix,
    required String? skillNoteId,
    required String? prompt,
    required bool? contentImmutable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerBinding, [], {
              #pattern: pattern,
              #isPrefix: isPrefix,
              #skillNoteId: skillNoteId,
              #prompt: prompt,
              #contentImmutable: contentImmutable,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeBinding(String? pattern) =>
      (super.noSuchMethod(
            Invocation.method(#removeBinding, [pattern]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AppProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppProvider extends _i1.Mock implements _i26.AppProvider {
  MockAppProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get newNoteFromShare =>
      (super.noSuchMethod(
            Invocation.getter(#newNoteFromShare),
            returnValue: false,
          )
          as bool);

  @override
  bool get onboardingCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingCompleted),
            returnValue: false,
          )
          as bool);

  @override
  List<_i9.Note> get notes =>
      (super.noSuchMethod(Invocation.getter(#notes), returnValue: <_i9.Note>[])
          as List<_i9.Note>);

  @override
  List<_i13.Tag> get tags =>
      (super.noSuchMethod(Invocation.getter(#tags), returnValue: <_i13.Tag>[])
          as List<_i13.Tag>);

  @override
  List<_i15.Filter> get filters =>
      (super.noSuchMethod(
            Invocation.getter(#filters),
            returnValue: <_i15.Filter>[],
          )
          as List<_i15.Filter>);

  @override
  List<_i7.UserApp> get userApps =>
      (super.noSuchMethod(
            Invocation.getter(#userApps),
            returnValue: <_i7.UserApp>[],
          )
          as List<_i7.UserApp>);

  @override
  Map<String, List<_i6.AppRevision>> get appRevisions =>
      (super.noSuchMethod(
            Invocation.getter(#appRevisions),
            returnValue: <String, List<_i6.AppRevision>>{},
          )
          as Map<String, List<_i6.AppRevision>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get dataVersion =>
      (super.noSuchMethod(Invocation.getter(#dataVersion), returnValue: 0)
          as int);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  _i5.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_3(this, Invocation.getter(#locale)),
          )
          as _i5.Locale);

  @override
  List<String> get multiFunctionApps =>
      (super.noSuchMethod(
            Invocation.getter(#multiFunctionApps),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isHierarchyEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isHierarchyEnabled),
            returnValue: false,
          )
          as bool);

  @override
  set newNoteFromShare(bool? value) => super.noSuchMethod(
    Invocation.setter(#newNoteFromShare, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> refreshNotesFromDb(Set<String>? noteIds) =>
      (super.noSuchMethod(
            Invocation.method(#refreshNotesFromDb, [noteIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void scheduleReload() => super.noSuchMethod(
    Invocation.method(#scheduleReload, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> loadData() =>
      (super.noSuchMethod(
            Invocation.method(#loadData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void updateModelConfig(_i23.ModelConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateModelConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> addNote(_i9.Note? note, {bool? fromShare = false}) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [note], {#fromShare: fromShare}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateNote(_i9.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateNoteContent(String? noteId, String? newContent) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteContent, [noteId, newContent]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateTaskStatus(String? noteId, _i9.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [noteId, status]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleNotePin(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleNotePin, [noteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [noteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addRelationship(_i14.Relationship? relationship) =>
      (super.noSuchMethod(
            Invocation.method(#addRelationship, [relationship]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRelationship(String? relationshipId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationship, [relationshipId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> createNoteRelationships(
    String? fromNoteId,
    List<String>? toNoteIds,
    String? relationshipType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteRelationships, [
              fromNoteId,
              toNoteIds,
              relationshipType,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i14.Relationship>> getNoteRelationships(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteRelationships, [noteId]),
            returnValue: _i8.Future<List<_i14.Relationship>>.value(
              <_i14.Relationship>[],
            ),
          )
          as _i8.Future<List<_i14.Relationship>>);

  @override
  _i8.Future<List<_i9.Note>> getLinkedNotes(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedNotes, [noteId]),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  _i8.Future<String> transformNote(
    _i9.Note? note,
    String? transformationPrompt, {
    List<_i24.PlatformFile>? attachedFiles,
    _i27.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformNote,
              [note, transformationPrompt],
              {
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(
                  #transformNote,
                  [note, transformationPrompt],
                  {
                    #attachedFiles: attachedFiles,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<List<_i9.Note>> createNewNotes(
    String? prompt,
    List<_i9.Note>? contextNotes, {
    List<_i24.PlatformFile>? attachedFiles,
    bool? persist = true,
    _i27.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createNewNotes,
              [prompt, contextNotes],
              {
                #attachedFiles: attachedFiles,
                #persist: persist,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i8.Future<List<_i9.Note>>.value(<_i9.Note>[]),
          )
          as _i8.Future<List<_i9.Note>>);

  @override
  List<_i9.Note> getNotesByTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByTag, [tagName]),
            returnValue: <_i9.Note>[],
          )
          as List<_i9.Note>);

  @override
  _i8.Future<void> addTagToNote(String? noteId, String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#addTagToNote, [noteId, tagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<String> getAllAvailableTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAvailableTags, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> refreshTags() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTags, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getTagExtractionPrompt(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagExtractionPrompt, [tagId]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> updateTagExtractionPrompt(String? tagId, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagExtractionPrompt, [tagId, prompt]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> replaceTag(String? oldTagName, String? newTagName) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTag, [oldTagName, newTagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i9.Note> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksForDate, [date]),
            returnValue: <_i9.Note>[],
          )
          as List<_i9.Note>);

  @override
  List<_i9.Note> getNotesForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesForDate, [date]),
            returnValue: <_i9.Note>[],
          )
          as List<_i9.Note>);

  @override
  double calculateTaskCompletionPercentage(_i9.Note? task) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTaskCompletionPercentage, [task]),
            returnValue: 0.0,
          )
          as double);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTheme() => super.noSuchMethod(
    Invocation.method(#toggleTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> loadThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadThemePreference, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void changeLanguage(_i5.Locale? locale) => super.noSuchMethod(
    Invocation.method(#changeLanguage, [locale]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> loadLanguagePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadLanguagePreference, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void toggleHierarchy() => super.noSuchMethod(
    Invocation.method(#toggleHierarchy, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> setOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
            Invocation.method(#setOnboardingCompleted, [completed]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addSubNoteToNote(String? noteId, _i9.SubNote? subNote) =>
      (super.noSuchMethod(
            Invocation.method(#addSubNoteToNote, [noteId, subNote]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateSubNoteInNote(
    String? noteId,
    _i9.SubNote? updatedSubNote,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubNoteInNote, [noteId, updatedSubNote]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteSubNoteFromNote(String? noteId, String? subNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubNoteFromNote, [noteId, subNoteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleSubNoteCompletion(String? noteId, String? subNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSubNoteCompletion, [noteId, subNoteId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeTagFromNote(String? noteId, String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromNote, [noteId, tagName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> batchUpdateTags(
    List<String>? noteIds,
    List<String>? tagsToAdd,
    List<String>? tagsToRemove,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateTags, [
              noteIds,
              tagsToAdd,
              tagsToRemove,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> upsertSubNoteInNote(String? noteId, _i9.SubNote? subNote) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSubNoteInNote, [noteId, subNote]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reparentSubNote(
    String? fromNoteId,
    String? toNoteId,
    _i9.SubNote? subNote,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reparentSubNote, [
              fromNoteId,
              toNoteId,
              subNote,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addFilter(_i15.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#addFilter, [filter]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateFilter(_i15.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#updateFilter, [filter]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteFilter(String? filterId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFilter, [filterId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i9.Note> getFilteredNotes(_i15.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredNotes, [filter]),
            returnValue: <_i9.Note>[],
          )
          as List<_i9.Note>);

  @override
  _i8.Future<void> addUserApp(_i7.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#addUserApp, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshUserApps() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserApps, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserApp(_i7.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserApp, [app]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.AppRevision> saveManualCodeEdit({
    required _i7.UserApp? originalApp,
    required String? newCode,
    List<String>? attachmentPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveManualCodeEdit, [], {
              #originalApp: originalApp,
              #newCode: newCode,
              #attachmentPaths: attachmentPaths,
            }),
            returnValue: _i8.Future<_i6.AppRevision>.value(
              _FakeAppRevision_4(
                this,
                Invocation.method(#saveManualCodeEdit, [], {
                  #originalApp: originalApp,
                  #newCode: newCode,
                  #attachmentPaths: attachmentPaths,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AppRevision>);

  @override
  _i8.Future<void> deleteUserApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserApp, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i7.UserApp> createUserApp({
    required String? name,
    required String? description,
    required List<String>? steps,
    _i7.UserAppType? type = _i7.UserAppType.normal,
    List<String>? attachmentPaths,
    List<_i9.Note>? contextNotes,
    List<_i7.UserAppLibraryInfo>? libraries,
    _i27.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserApp, [], {
              #name: name,
              #description: description,
              #steps: steps,
              #type: type,
              #attachmentPaths: attachmentPaths,
              #contextNotes: contextNotes,
              #libraries: libraries,
              #generationContext: generationContext,
            }),
            returnValue: _i8.Future<_i7.UserApp>.value(
              _FakeUserApp_5(
                this,
                Invocation.method(#createUserApp, [], {
                  #name: name,
                  #description: description,
                  #steps: steps,
                  #type: type,
                  #attachmentPaths: attachmentPaths,
                  #contextNotes: contextNotes,
                  #libraries: libraries,
                  #generationContext: generationContext,
                }),
              ),
            ),
          )
          as _i8.Future<_i7.UserApp>);

  @override
  _i8.Future<_i6.AppRevision> editUserApp({
    required _i7.UserApp? originalApp,
    required String? editSuggestion,
    List<String>? attachmentPaths,
    List<_i9.Note>? contextNotes,
    List<_i7.UserAppLibraryInfo>? libraries,
    _i27.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editUserApp, [], {
              #originalApp: originalApp,
              #editSuggestion: editSuggestion,
              #attachmentPaths: attachmentPaths,
              #contextNotes: contextNotes,
              #libraries: libraries,
              #generationContext: generationContext,
            }),
            returnValue: _i8.Future<_i6.AppRevision>.value(
              _FakeAppRevision_4(
                this,
                Invocation.method(#editUserApp, [], {
                  #originalApp: originalApp,
                  #editSuggestion: editSuggestion,
                  #attachmentPaths: attachmentPaths,
                  #contextNotes: contextNotes,
                  #libraries: libraries,
                  #generationContext: generationContext,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.AppRevision>);

  @override
  _i8.Future<Map<String, dynamic>?> getAppState(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppState, [appId]),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> saveAppState(String? appId, Map<String, dynamic>? state) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppState, [appId, state]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i6.AppRevision>> getAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevisions, [appId]),
            returnValue: _i8.Future<List<_i6.AppRevision>>.value(
              <_i6.AppRevision>[],
            ),
          )
          as _i8.Future<List<_i6.AppRevision>>);

  @override
  _i8.Future<_i6.AppRevision?> getAppRevision(String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevision, [revisionId]),
            returnValue: _i8.Future<_i6.AppRevision?>.value(),
          )
          as _i8.Future<_i6.AppRevision?>);

  @override
  _i8.Future<void> deleteAppRevision(String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevision, [revisionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setSelectedRevision(String? appId, String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedRevision, [appId, revisionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAppRevisions, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearAppRevisionsCache(String? appId) => super.noSuchMethod(
    Invocation.method(#clearAppRevisionsCache, [appId]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i6.AppRevision> createInitialRevision(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#createInitialRevision, [appId]),
            returnValue: _i8.Future<_i6.AppRevision>.value(
              _FakeAppRevision_4(
                this,
                Invocation.method(#createInitialRevision, [appId]),
              ),
            ),
          )
          as _i8.Future<_i6.AppRevision>);

  @override
  bool isWebViewSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isWebViewSupported, []),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getNoteConversationCount(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationCount, [noteId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<String>> getNoteConversationIds(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationIds, [noteId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> addAppToMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#addAppToMultiFunction, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> removeAppFromMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppFromMultiFunction, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setMultiFunctionDefaultApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setMultiFunctionDefaultApp, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearMultiFunctionDefaultApp() =>
      (super.noSuchMethod(
            Invocation.method(#clearMultiFunctionDefaultApp, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setCurrentMultiFunctionApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentMultiFunctionApp, [appId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> toggleFilterPin(String? filterId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFilterPin, [filterId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
