// Mocks generated by Mockito 5.4.6 from annotations
// in note_synapse/test/services/share_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i2;

import 'package:file_picker/file_picker.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:note_synapse/models/app_revision.dart' as _i3;
import 'package:note_synapse/models/filter.dart' as _i8;
import 'package:note_synapse/models/generation_context.dart' as _i13;
import 'package:note_synapse/models/model_config.dart' as _i10;
import 'package:note_synapse/models/note.dart' as _i6;
import 'package:note_synapse/models/relationship.dart' as _i11;
import 'package:note_synapse/models/tag.dart' as _i7;
import 'package:note_synapse/models/user_app.dart' as _i4;
import 'package:note_synapse/providers/app_provider.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocale_0 extends _i1.SmartFake implements _i2.Locale {
  _FakeLocale_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppRevision_1 extends _i1.SmartFake implements _i3.AppRevision {
  _FakeAppRevision_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserApp_2 extends _i1.SmartFake implements _i4.UserApp {
  _FakeUserApp_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppProvider extends _i1.Mock implements _i5.AppProvider {
  MockAppProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get newNoteFromShare =>
      (super.noSuchMethod(
            Invocation.getter(#newNoteFromShare),
            returnValue: false,
          )
          as bool);

  @override
  bool get onboardingCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#onboardingCompleted),
            returnValue: false,
          )
          as bool);

  @override
  List<_i6.Note> get notes =>
      (super.noSuchMethod(Invocation.getter(#notes), returnValue: <_i6.Note>[])
          as List<_i6.Note>);

  @override
  bool get hasLoadedOnce =>
      (super.noSuchMethod(Invocation.getter(#hasLoadedOnce), returnValue: false)
          as bool);

  @override
  List<_i7.Tag> get tags =>
      (super.noSuchMethod(Invocation.getter(#tags), returnValue: <_i7.Tag>[])
          as List<_i7.Tag>);

  @override
  List<_i8.Filter> get filters =>
      (super.noSuchMethod(
            Invocation.getter(#filters),
            returnValue: <_i8.Filter>[],
          )
          as List<_i8.Filter>);

  @override
  List<_i4.UserApp> get userApps =>
      (super.noSuchMethod(
            Invocation.getter(#userApps),
            returnValue: <_i4.UserApp>[],
          )
          as List<_i4.UserApp>);

  @override
  Map<String, List<_i3.AppRevision>> get appRevisions =>
      (super.noSuchMethod(
            Invocation.getter(#appRevisions),
            returnValue: <String, List<_i3.AppRevision>>{},
          )
          as Map<String, List<_i3.AppRevision>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get dataVersion =>
      (super.noSuchMethod(Invocation.getter(#dataVersion), returnValue: 0)
          as int);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  _i2.Locale get locale =>
      (super.noSuchMethod(
            Invocation.getter(#locale),
            returnValue: _FakeLocale_0(this, Invocation.getter(#locale)),
          )
          as _i2.Locale);

  @override
  List<String> get multiFunctionApps =>
      (super.noSuchMethod(
            Invocation.getter(#multiFunctionApps),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isHierarchyEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isHierarchyEnabled),
            returnValue: false,
          )
          as bool);

  @override
  set newNoteFromShare(bool? value) => super.noSuchMethod(
    Invocation.setter(#newNoteFromShare, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<void> refreshNotesFromDb(Set<String>? noteIds) =>
      (super.noSuchMethod(
            Invocation.method(#refreshNotesFromDb, [noteIds]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void scheduleReload() => super.noSuchMethod(
    Invocation.method(#scheduleReload, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> loadData() =>
      (super.noSuchMethod(
            Invocation.method(#loadData, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void updateModelConfig(_i10.ModelConfig? newConfig) => super.noSuchMethod(
    Invocation.method(#updateModelConfig, [newConfig]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> addNote(_i6.Note? note, {bool? fromShare = false}) =>
      (super.noSuchMethod(
            Invocation.method(#addNote, [note], {#fromShare: fromShare}),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateNote(_i6.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateNoteContent(String? noteId, String? newContent) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteContent, [noteId, newContent]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateTaskStatus(String? noteId, _i6.TaskStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskStatus, [noteId, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> toggleNotePin(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleNotePin, [noteId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteNote(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [noteId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> addRelationship(_i11.Relationship? relationship) =>
      (super.noSuchMethod(
            Invocation.method(#addRelationship, [relationship]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteRelationship(String? relationshipId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRelationship, [relationshipId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> createNoteRelationships(
    String? fromNoteId,
    List<String>? toNoteIds,
    String? relationshipType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNoteRelationships, [
              fromNoteId,
              toNoteIds,
              relationshipType,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i11.Relationship>> getNoteRelationships(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteRelationships, [noteId]),
            returnValue: _i9.Future<List<_i11.Relationship>>.value(
              <_i11.Relationship>[],
            ),
          )
          as _i9.Future<List<_i11.Relationship>>);

  @override
  _i9.Future<List<_i6.Note>> getLinkedNotes(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedNotes, [noteId]),
            returnValue: _i9.Future<List<_i6.Note>>.value(<_i6.Note>[]),
          )
          as _i9.Future<List<_i6.Note>>);

  @override
  _i9.Future<String> transformNote(
    _i6.Note? note,
    String? transformationPrompt, {
    List<_i12.PlatformFile>? attachedFiles,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transformNote,
              [note, transformationPrompt],
              {
                #attachedFiles: attachedFiles,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i9.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(
                  #transformNote,
                  [note, transformationPrompt],
                  {
                    #attachedFiles: attachedFiles,
                    #generationContext: generationContext,
                  },
                ),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<List<_i6.Note>> createNewNotes(
    String? prompt,
    List<_i6.Note>? contextNotes, {
    List<_i12.PlatformFile>? attachedFiles,
    bool? persist = true,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createNewNotes,
              [prompt, contextNotes],
              {
                #attachedFiles: attachedFiles,
                #persist: persist,
                #generationContext: generationContext,
              },
            ),
            returnValue: _i9.Future<List<_i6.Note>>.value(<_i6.Note>[]),
          )
          as _i9.Future<List<_i6.Note>>);

  @override
  List<_i6.Note> getNotesByTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByTag, [tagName]),
            returnValue: <_i6.Note>[],
          )
          as List<_i6.Note>);

  @override
  _i9.Future<void> addTagToNote(String? noteId, String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#addTagToNote, [noteId, tagName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  List<String> getAllAvailableTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAvailableTags, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> refreshTags() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTags, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String?> getTagExtractionPrompt(String? tagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTagExtractionPrompt, [tagId]),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> updateTagExtractionPrompt(String? tagId, String? prompt) =>
      (super.noSuchMethod(
            Invocation.method(#updateTagExtractionPrompt, [tagId, prompt]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tagName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> replaceTag(String? oldTagName, String? newTagName) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTag, [oldTagName, newTagName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  List<_i6.Note> getTasksForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getTasksForDate, [date]),
            returnValue: <_i6.Note>[],
          )
          as List<_i6.Note>);

  @override
  List<_i6.Note> getNotesForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesForDate, [date]),
            returnValue: <_i6.Note>[],
          )
          as List<_i6.Note>);

  @override
  double calculateTaskCompletionPercentage(_i6.Note? task) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTaskCompletionPercentage, [task]),
            returnValue: 0.0,
          )
          as double);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void toggleTheme() => super.noSuchMethod(
    Invocation.method(#toggleTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> loadThemePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadThemePreference, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void changeLanguage(_i2.Locale? locale) => super.noSuchMethod(
    Invocation.method(#changeLanguage, [locale]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> loadLanguagePreference() =>
      (super.noSuchMethod(
            Invocation.method(#loadLanguagePreference, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void toggleHierarchy() => super.noSuchMethod(
    Invocation.method(#toggleHierarchy, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> setOnboardingCompleted(bool? completed) =>
      (super.noSuchMethod(
            Invocation.method(#setOnboardingCompleted, [completed]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> addSubNoteToNote(String? noteId, _i6.SubNote? subNote) =>
      (super.noSuchMethod(
            Invocation.method(#addSubNoteToNote, [noteId, subNote]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateSubNoteInNote(
    String? noteId,
    _i6.SubNote? updatedSubNote,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubNoteInNote, [noteId, updatedSubNote]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteSubNoteFromNote(String? noteId, String? subNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubNoteFromNote, [noteId, subNoteId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> toggleSubNoteCompletion(String? noteId, String? subNoteId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleSubNoteCompletion, [noteId, subNoteId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeTagFromNote(String? noteId, String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromNote, [noteId, tagName]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> batchUpdateTags(
    List<String>? noteIds,
    List<String>? tagsToAdd,
    List<String>? tagsToRemove,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateTags, [
              noteIds,
              tagsToAdd,
              tagsToRemove,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> upsertSubNoteInNote(String? noteId, _i6.SubNote? subNote) =>
      (super.noSuchMethod(
            Invocation.method(#upsertSubNoteInNote, [noteId, subNote]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> reparentSubNote(
    String? fromNoteId,
    String? toNoteId,
    _i6.SubNote? subNote,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reparentSubNote, [
              fromNoteId,
              toNoteId,
              subNote,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> addFilter(_i8.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#addFilter, [filter]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateFilter(_i8.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#updateFilter, [filter]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteFilter(String? filterId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFilter, [filterId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  List<_i6.Note> getFilteredNotes(_i8.Filter? filter) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredNotes, [filter]),
            returnValue: <_i6.Note>[],
          )
          as List<_i6.Note>);

  @override
  _i9.Future<void> addUserApp(_i4.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#addUserApp, [app]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshUserApps() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserApps, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> updateUserApp(_i4.UserApp? app) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserApp, [app]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.AppRevision> saveManualCodeEdit({
    required _i4.UserApp? originalApp,
    required String? newCode,
    List<String>? attachmentPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveManualCodeEdit, [], {
              #originalApp: originalApp,
              #newCode: newCode,
              #attachmentPaths: attachmentPaths,
            }),
            returnValue: _i9.Future<_i3.AppRevision>.value(
              _FakeAppRevision_1(
                this,
                Invocation.method(#saveManualCodeEdit, [], {
                  #originalApp: originalApp,
                  #newCode: newCode,
                  #attachmentPaths: attachmentPaths,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AppRevision>);

  @override
  _i9.Future<void> deleteUserApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserApp, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.UserApp> createUserApp({
    required String? name,
    required String? description,
    required List<String>? steps,
    _i4.UserAppType? type = _i4.UserAppType.normal,
    List<String>? attachmentPaths,
    List<_i6.Note>? contextNotes,
    List<_i4.UserAppLibraryInfo>? libraries,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserApp, [], {
              #name: name,
              #description: description,
              #steps: steps,
              #type: type,
              #attachmentPaths: attachmentPaths,
              #contextNotes: contextNotes,
              #libraries: libraries,
              #generationContext: generationContext,
            }),
            returnValue: _i9.Future<_i4.UserApp>.value(
              _FakeUserApp_2(
                this,
                Invocation.method(#createUserApp, [], {
                  #name: name,
                  #description: description,
                  #steps: steps,
                  #type: type,
                  #attachmentPaths: attachmentPaths,
                  #contextNotes: contextNotes,
                  #libraries: libraries,
                  #generationContext: generationContext,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.UserApp>);

  @override
  _i9.Future<_i3.AppRevision> editUserApp({
    required _i4.UserApp? originalApp,
    required String? editSuggestion,
    List<String>? attachmentPaths,
    List<_i6.Note>? contextNotes,
    List<_i4.UserAppLibraryInfo>? libraries,
    _i13.GenerationContext? generationContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editUserApp, [], {
              #originalApp: originalApp,
              #editSuggestion: editSuggestion,
              #attachmentPaths: attachmentPaths,
              #contextNotes: contextNotes,
              #libraries: libraries,
              #generationContext: generationContext,
            }),
            returnValue: _i9.Future<_i3.AppRevision>.value(
              _FakeAppRevision_1(
                this,
                Invocation.method(#editUserApp, [], {
                  #originalApp: originalApp,
                  #editSuggestion: editSuggestion,
                  #attachmentPaths: attachmentPaths,
                  #contextNotes: contextNotes,
                  #libraries: libraries,
                  #generationContext: generationContext,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.AppRevision>);

  @override
  _i9.Future<Map<String, dynamic>?> getAppState(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppState, [appId]),
            returnValue: _i9.Future<Map<String, dynamic>?>.value(),
          )
          as _i9.Future<Map<String, dynamic>?>);

  @override
  _i9.Future<void> saveAppState(String? appId, Map<String, dynamic>? state) =>
      (super.noSuchMethod(
            Invocation.method(#saveAppState, [appId, state]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.AppRevision>> getAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevisions, [appId]),
            returnValue: _i9.Future<List<_i3.AppRevision>>.value(
              <_i3.AppRevision>[],
            ),
          )
          as _i9.Future<List<_i3.AppRevision>>);

  @override
  _i9.Future<_i3.AppRevision?> getAppRevision(String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#getAppRevision, [revisionId]),
            returnValue: _i9.Future<_i3.AppRevision?>.value(),
          )
          as _i9.Future<_i3.AppRevision?>);

  @override
  _i9.Future<void> deleteAppRevision(String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAppRevision, [revisionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setSelectedRevision(String? appId, String? revisionId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedRevision, [appId, revisionId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> refreshAppRevisions(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#refreshAppRevisions, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearAppRevisionsCache(String? appId) => super.noSuchMethod(
    Invocation.method(#clearAppRevisionsCache, [appId]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<_i3.AppRevision> createInitialRevision(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#createInitialRevision, [appId]),
            returnValue: _i9.Future<_i3.AppRevision>.value(
              _FakeAppRevision_1(
                this,
                Invocation.method(#createInitialRevision, [appId]),
              ),
            ),
          )
          as _i9.Future<_i3.AppRevision>);

  @override
  bool isWebViewSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isWebViewSupported, []),
            returnValue: false,
          )
          as bool);

  @override
  _i9.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<int> getNoteConversationCount(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationCount, [noteId]),
            returnValue: _i9.Future<int>.value(0),
          )
          as _i9.Future<int>);

  @override
  _i9.Future<List<String>> getNoteConversationIds(String? noteId) =>
      (super.noSuchMethod(
            Invocation.method(#getNoteConversationIds, [noteId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> addAppToMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#addAppToMultiFunction, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeAppFromMultiFunction(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#removeAppFromMultiFunction, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setMultiFunctionDefaultApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setMultiFunctionDefaultApp, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> clearMultiFunctionDefaultApp() =>
      (super.noSuchMethod(
            Invocation.method(#clearMultiFunctionDefaultApp, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setCurrentMultiFunctionApp(String? appId) =>
      (super.noSuchMethod(
            Invocation.method(#setCurrentMultiFunctionApp, [appId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> toggleFilterPin(String? filterId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFilterPin, [filterId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
