// Mocks generated by Mockito 5.4.6 from annotations
// in note_synapse/test/spaces/conversation_tree_space_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:note_synapse/models/conversation.dart' as _i3;
import 'package:note_synapse/models/conversation_branch_summary.dart' as _i13;
import 'package:note_synapse/models/conversation_context.dart' as _i4;
import 'package:note_synapse/models/mcp_endpoint.dart' as _i7;
import 'package:note_synapse/models/note.dart' as _i12;
import 'package:note_synapse/models/tag.dart' as _i11;
import 'package:note_synapse/services/ai_tool_service.dart' as _i8;
import 'package:note_synapse/services/conversation_service.dart' as _i5;
import 'package:note_synapse/services/skill_service.dart' as _i6;
import 'package:note_synapse/services/tools/load_skill_tool.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoadSkillTool_0 extends _i1.SmartFake implements _i2.LoadSkillTool {
  _FakeLoadSkillTool_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversation_1 extends _i1.SmartFake implements _i3.Conversation {
  _FakeConversation_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForkContextSelection_2 extends _i1.SmartFake
    implements _i4.ForkContextSelection {
  _FakeForkContextSelection_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationMessage_3 extends _i1.SmartFake
    implements _i3.ConversationMessage {
  _FakeConversationMessage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConversationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationService extends _i1.Mock
    implements _i5.ConversationService {
  MockConversationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get skillsEnabled =>
      (super.noSuchMethod(Invocation.getter(#skillsEnabled), returnValue: false)
          as bool);

  @override
  Map<String, _i6.SkillMetadata> get skillIndex =>
      (super.noSuchMethod(
            Invocation.getter(#skillIndex),
            returnValue: <String, _i6.SkillMetadata>{},
          )
          as Map<String, _i6.SkillMetadata>);

  @override
  bool get isSkillIndexStale =>
      (super.noSuchMethod(
            Invocation.getter(#isSkillIndexStale),
            returnValue: false,
          )
          as bool);

  @override
  List<_i7.McpTool> get skillDiscoveredTools =>
      (super.noSuchMethod(
            Invocation.getter(#skillDiscoveredTools),
            returnValue: <_i7.McpTool>[],
          )
          as List<_i7.McpTool>);

  @override
  Map<String, String> get skillToolEndpointNames =>
      (super.noSuchMethod(
            Invocation.getter(#skillToolEndpointNames),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> get skillToolEndpointIds =>
      (super.noSuchMethod(
            Invocation.getter(#skillToolEndpointIds),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, _i8.AiToolAppBundle> get skillDiscoveredBundles =>
      (super.noSuchMethod(
            Invocation.getter(#skillDiscoveredBundles),
            returnValue: <String, _i8.AiToolAppBundle>{},
          )
          as Map<String, _i8.AiToolAppBundle>);

  @override
  Set<String> get skillDiscoveredNativeToolNames =>
      (super.noSuchMethod(
            Invocation.getter(#skillDiscoveredNativeToolNames),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  _i2.LoadSkillTool get loadSkillTool =>
      (super.noSuchMethod(
            Invocation.getter(#loadSkillTool),
            returnValue: _FakeLoadSkillTool_0(
              this,
              Invocation.getter(#loadSkillTool),
            ),
          )
          as _i2.LoadSkillTool);

  @override
  _i9.Future<Map<String, _i6.SkillMetadata>> ensureSkillIndex() =>
      (super.noSuchMethod(
            Invocation.method(#ensureSkillIndex, []),
            returnValue: _i9.Future<Map<String, _i6.SkillMetadata>>.value(
              <String, _i6.SkillMetadata>{},
            ),
          )
          as _i9.Future<Map<String, _i6.SkillMetadata>>);

  @override
  _i9.Future<void> enableSkills() =>
      (super.noSuchMethod(
            Invocation.method(#enableSkills, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void disableSkills() => super.noSuchMethod(
    Invocation.method(#disableSkills, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> handleLoadSkillResult(String? noteId, String? result) =>
      (super.noSuchMethod(
            Invocation.method(#handleLoadSkillResult, [noteId, result]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.Conversation> createConversation({
    required String? title,
    List<String>? noteIds = const [],
    List<String>? tags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversation, [], {
              #title: title,
              #noteIds: noteIds,
              #tags: tags,
            }),
            returnValue: _i9.Future<_i3.Conversation>.value(
              _FakeConversation_1(
                this,
                Invocation.method(#createConversation, [], {
                  #title: title,
                  #noteIds: noteIds,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Conversation>);

  @override
  _i9.Future<_i3.Conversation> forkConversation({
    required String? originalConversationId,
    required String? forkFromMessageId,
    required String? newTitle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forkConversation, [], {
              #originalConversationId: originalConversationId,
              #forkFromMessageId: forkFromMessageId,
              #newTitle: newTitle,
            }),
            returnValue: _i9.Future<_i3.Conversation>.value(
              _FakeConversation_1(
                this,
                Invocation.method(#forkConversation, [], {
                  #originalConversationId: originalConversationId,
                  #forkFromMessageId: forkFromMessageId,
                  #newTitle: newTitle,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Conversation>);

  @override
  _i9.Future<_i4.ForkContextSelection> prepareForkContextSelection(
    String? forkFromMessageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#prepareForkContextSelection, [
              forkFromMessageId,
            ]),
            returnValue: _i9.Future<_i4.ForkContextSelection>.value(
              _FakeForkContextSelection_2(
                this,
                Invocation.method(#prepareForkContextSelection, [
                  forkFromMessageId,
                ]),
              ),
            ),
          )
          as _i9.Future<_i4.ForkContextSelection>);

  @override
  _i9.Future<_i3.Conversation> forkConversationWithContext({
    required String? forkFromMessageId,
    required _i4.ConversationContext? selectedContext,
    required String? newTitle,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forkConversationWithContext, [], {
              #forkFromMessageId: forkFromMessageId,
              #selectedContext: selectedContext,
              #newTitle: newTitle,
            }),
            returnValue: _i9.Future<_i3.Conversation>.value(
              _FakeConversation_1(
                this,
                Invocation.method(#forkConversationWithContext, [], {
                  #forkFromMessageId: forkFromMessageId,
                  #selectedContext: selectedContext,
                  #newTitle: newTitle,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Conversation>);

  @override
  _i9.Future<_i3.ConversationMessage> addUserMessage({
    required String? conversationId,
    required String? content,
    List<String>? attachmentPaths = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessage, [], {
              #conversationId: conversationId,
              #content: content,
              #attachmentPaths: attachmentPaths,
            }),
            returnValue: _i9.Future<_i3.ConversationMessage>.value(
              _FakeConversationMessage_3(
                this,
                Invocation.method(#addUserMessage, [], {
                  #conversationId: conversationId,
                  #content: content,
                  #attachmentPaths: attachmentPaths,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.ConversationMessage>);

  @override
  _i9.Future<_i3.ConversationMessage> addAIResponse({
    required String? conversationId,
    required String? content,
    String? modelUsed,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addAIResponse, [], {
              #conversationId: conversationId,
              #content: content,
              #modelUsed: modelUsed,
              #metadata: metadata,
            }),
            returnValue: _i9.Future<_i3.ConversationMessage>.value(
              _FakeConversationMessage_3(
                this,
                Invocation.method(#addAIResponse, [], {
                  #conversationId: conversationId,
                  #content: content,
                  #modelUsed: modelUsed,
                  #metadata: metadata,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.ConversationMessage>);

  @override
  _i9.Future<void> updateConversationMessage(
    _i3.ConversationMessage? message,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationMessage, [message]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.Conversation>> getAllConversations({
    Duration? maxAge,
    List<String>? tagNames,
    List<String>? scopeTags,
    List<String>? conversationIds,
    bool? includeEmpty = true,
    bool? includeAllSpacesTag = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, [], {
              #maxAge: maxAge,
              #tagNames: tagNames,
              #scopeTags: scopeTags,
              #conversationIds: conversationIds,
              #includeEmpty: includeEmpty,
              #includeAllSpacesTag: includeAllSpacesTag,
            }),
            returnValue: _i9.Future<List<_i3.Conversation>>.value(
              <_i3.Conversation>[],
            ),
          )
          as _i9.Future<List<_i3.Conversation>>);

  @override
  _i9.Future<List<_i3.ConversationMessage>> getConversationPreviewMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationPreviewMessages, [
              conversationId,
            ]),
            returnValue: _i9.Future<List<_i3.ConversationMessage>>.value(
              <_i3.ConversationMessage>[],
            ),
          )
          as _i9.Future<List<_i3.ConversationMessage>>);

  @override
  _i9.Future<_i3.Conversation?> getConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [conversationId]),
            returnValue: _i9.Future<_i3.Conversation?>.value(),
          )
          as _i9.Future<_i3.Conversation?>);

  @override
  _i9.Future<void> renameConversation({
    required String? conversationId,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#renameConversation, [], {
              #conversationId: conversationId,
              #title: title,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i3.ConversationMessage>> getConversationMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessages, [conversationId]),
            returnValue: _i9.Future<List<_i3.ConversationMessage>>.value(
              <_i3.ConversationMessage>[],
            ),
          )
          as _i9.Future<List<_i3.ConversationMessage>>);

  @override
  _i9.Future<_i5.ConversationWithMessages?> getConversationWithMessages(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationWithMessages, [conversationId]),
            returnValue: _i9.Future<_i5.ConversationWithMessages?>.value(),
          )
          as _i9.Future<_i5.ConversationWithMessages?>);

  @override
  _i9.Future<_i5.ConversationWithMessages?> getConversationWithFullHistory(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationWithFullHistory, [
              conversationId,
            ]),
            returnValue: _i9.Future<_i5.ConversationWithMessages?>.value(),
          )
          as _i9.Future<_i5.ConversationWithMessages?>);

  @override
  _i9.Future<List<String>> validateConversationNotes(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#validateConversationNotes, [conversationId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> cleanupInvalidNoteReferences() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupInvalidNoteReferences, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.ConversationTree?> getConversationTree({
    Duration? maxAge,
    List<String>? conversationIds,
    List<String>? tagNames,
    List<String>? scopeTags,
    bool? includeAllSpacesTag = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTree, [], {
              #maxAge: maxAge,
              #conversationIds: conversationIds,
              #tagNames: tagNames,
              #scopeTags: scopeTags,
              #includeAllSpacesTag: includeAllSpacesTag,
            }),
            returnValue: _i9.Future<_i3.ConversationTree?>.value(),
          )
          as _i9.Future<_i3.ConversationTree?>);

  @override
  _i9.Future<_i3.ConversationTree?> refreshConversationTree({
    Duration? maxAge,
    List<String>? conversationIds,
    List<String>? tagNames,
    List<String>? scopeTags,
    bool? includeAllSpacesTag = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#refreshConversationTree, [], {
              #maxAge: maxAge,
              #conversationIds: conversationIds,
              #tagNames: tagNames,
              #scopeTags: scopeTags,
              #includeAllSpacesTag: includeAllSpacesTag,
            }),
            returnValue: _i9.Future<_i3.ConversationTree?>.value(),
          )
          as _i9.Future<_i3.ConversationTree?>);

  @override
  _i9.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteMessageWithSubtree(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessageWithSubtree, [messageId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteMessagesFromTreeNodes(List<String>? messageIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessagesFromTreeNodes, [messageIds]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<String>> getMessageIdsFromTreeNode(
    _i3.ConversationTreeNode? node,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageIdsFromTreeNode, [node]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<List<String>> getAllMessageIdsInSubtree(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMessageIdsInSubtree, [messageId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<_i3.Conversation> createConversationFromSelectedNodes({
    required List<String>? selectedNodeIds,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createConversationFromSelectedNodes, [], {
              #selectedNodeIds: selectedNodeIds,
              #title: title,
            }),
            returnValue: _i9.Future<_i3.Conversation>.value(
              _FakeConversation_1(
                this,
                Invocation.method(#createConversationFromSelectedNodes, [], {
                  #selectedNodeIds: selectedNodeIds,
                  #title: title,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.Conversation>);

  @override
  _i9.Future<List<_i5.ConversationInteractionSnippet>>
  buildInteractionSnippets({
    _i3.ConversationTree? existingTree,
    required List<String>? nodeIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#buildInteractionSnippets, [], {
              #existingTree: existingTree,
              #nodeIds: nodeIds,
            }),
            returnValue:
                _i9.Future<List<_i5.ConversationInteractionSnippet>>.value(
                  <_i5.ConversationInteractionSnippet>[],
                ),
          )
          as _i9.Future<List<_i5.ConversationInteractionSnippet>>);

  @override
  String formatInteractionSnippets(
    List<_i5.ConversationInteractionSnippet>? snippets,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#formatInteractionSnippets, [snippets]),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#formatInteractionSnippets, [snippets]),
            ),
          )
          as String);

  @override
  _i9.Future<List<_i11.Tag>> getConversationTags(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTags, [conversationId]),
            returnValue: _i9.Future<List<_i11.Tag>>.value(<_i11.Tag>[]),
          )
          as _i9.Future<List<_i11.Tag>>);

  @override
  _i9.Future<List<String>> getConversationTagNames(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationTagNames, [conversationId]),
            returnValue: _i9.Future<List<String>>.value(<String>[]),
          )
          as _i9.Future<List<String>>);

  @override
  _i9.Future<void> addTagsToConversation(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addTagsToConversation, [
              conversationId,
              tagNames,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> setConversationTags(
    String? conversationId,
    List<String>? tagNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConversationTags, [conversationId, tagNames]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeTagFromConversation(
    String? conversationId,
    String? tagName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeTagFromConversation, [
              conversationId,
              tagName,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i12.Note>> getConversationNotes(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationNotes, [conversationId]),
            returnValue: _i9.Future<List<_i12.Note>>.value(<_i12.Note>[]),
          )
          as _i9.Future<List<_i12.Note>>);

  @override
  _i9.Future<List<_i12.Note>> getNotesByIds(List<String>? noteIds) =>
      (super.noSuchMethod(
            Invocation.method(#getNotesByIds, [noteIds]),
            returnValue: _i9.Future<List<_i12.Note>>.value(<_i12.Note>[]),
          )
          as _i9.Future<List<_i12.Note>>);

  @override
  _i9.Future<void> addNotesToConversation(
    String? conversationId,
    List<String>? noteIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNotesToConversation, [
              conversationId,
              noteIds,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> removeNotesFromConversation(
    String? conversationId,
    List<String>? noteIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeNotesFromConversation, [
              conversationId,
              noteIds,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> deleteEmptyConversations({required Duration? olderThan}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmptyConversations, [], {
              #olderThan: olderThan,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i3.ConversationMessage?> getConversationMessage(
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationMessage, [messageId]),
            returnValue: _i9.Future<_i3.ConversationMessage?>.value(),
          )
          as _i9.Future<_i3.ConversationMessage?>);

  @override
  _i9.Future<List<_i13.ConversationBranchSummary>> getChildBranches(
    String? parentMessageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChildBranches, [parentMessageId]),
            returnValue: _i9.Future<List<_i13.ConversationBranchSummary>>.value(
              <_i13.ConversationBranchSummary>[],
            ),
          )
          as _i9.Future<List<_i13.ConversationBranchSummary>>);

  @override
  _i9.Future<Map<String, List<_i13.ConversationBranchSummary>>>
  getAllForkPointBranches(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllForkPointBranches, [conversationId]),
            returnValue:
                _i9.Future<
                  Map<String, List<_i13.ConversationBranchSummary>>
                >.value(<String, List<_i13.ConversationBranchSummary>>{}),
          )
          as _i9.Future<Map<String, List<_i13.ConversationBranchSummary>>>);
}
